### ISSUE TITLE
Falsches state durch js-controller / Admin 5.x. Update

### ISSUE THREAD

**Issue by JBSullivan** [iobroker-community-adapters/ioBroker.spotify-premium#101]
`
<html>
<body>

spotify-premium.0 | 2021-05-13 08:41:11.826 | info | (13860) State value to set for "spotify-premium.0.playlists.117911346-1zfcZcDPbAEzJFre6QPvHB.trackListArray" has to be stringified but received type "object"
-- | -- | -- | --

</body>
</html>`

**Comment by Apollon77** [comment]
duplicate #95, try github action
