### ISSUE TITLE
some Errors on 1.1.3 leading to adapter crash - Logs here. 

### ISSUE THREAD

**Issue by cavernerg** [iobroker-community-adapters/ioBroker.spotify-premium#105]
Adapter 1.1.3
Nodejs 12.22.2
Host 3.3.15

If more infos needed, please comment 

```
<html><body>
<!--StartFragment-->

spotify-premium.0 | 2021-08-21 11:52:51.147 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
-- | -- | -- | --
spotify-premium.0 | 2021-08-21 11:52:51.147 | info | terminating
spotify-premium.0 | 2021-08-21 11:52:51.097 | info | State value to set for "spotify-premium.0.player.playlist.trackNo" has to be type "number" but received type "string"
spotify-premium.0 | 2021-08-21 11:52:51.083 | debug | save state: info.connection -> false
spotify-premium.0 | 2021-08-21 11:52:51.083 | debug | save state: player.playlist.owner -> ""
spotify-premium.0 | 2021-08-21 11:52:51.083 | debug | save state: player.playlist.trackNo -> ""
spotify-premium.0 | 2021-08-21 11:52:51.083 | debug | save state: authorization.authorized -> false
spotify-premium.0 | 2021-08-21 11:52:51.083 | debug | save state: player.playlist.id -> ""
spotify-premium.0 | 2021-08-21 11:52:51.082 | debug | save state: player.trackId -> ""
spotify-premium.0 | 2021-08-21 11:52:51.082 | debug | save state: authorization.userId -> ""
spotify-premium.0 | 2021-08-21 11:52:51.079 | error | TypeError:  Cannot read property 'name' of undefined    at  Object.listenOnHtmlTracklist [as func]  (/opt/iobroker/node_modules/iobroker.spotify-premium/main.js:2035:33)     at  /opt/iobroker/node_modules/iobroker.spotify-premium/lib/cache.js:229:19     at Array.forEach (<anonymous>)    at trigger  (/opt/iobroker/node_modules/iobroker.spotify-premium/lib/cache.js:223:14)     at Object.setValue  (/opt/iobroker/node_modules/iobroker.spotify-premium/lib/cache.js:213:13)     at copyState  (/opt/iobroker/node_modules/iobroker.spotify-premium/main.js:435:18)     at /opt/iobroker/node_modules/iobroker.spotify-premium/main.js:666:37
spotify-premium.0 | 2021-08-21 11:52:51.078 | error | unhandled promise rejection: Cannot read property 'name' of undefined
spotify-premium.0 | 2021-08-21 11:52:51.079 | error | Cannot read property 'name' of undefined
spotify-premium.0 | 2021-08-21 11:52:51.078 | error | Unhandled  promise rejection. This error originated either by throwing inside of  an async function without a catch block, or by rejecting a promise which  was not handled with .catch().

<!--EndFragment-->
</body>
</html>
```

**Comment by simonssoftware** [comment]
Same problem here.

**Comment by Spremse** [comment]
Nach Update auf 1.1.3 wird Adapter vom System deaktiviert. Folgende Logs:

- error: instance system.adapter.spotify-premium.0 terminated with code 3 (NO_ADAPTER_CONFIG_FOUND)

- error: adapter disabled <--- Error von Spotfy Instanz

- error: instance system.adapter.spotify-premium.0 terminated with code 6 (UNCAUGHT_EXCEPTION) <--- Error vom Host

- warn: Terminated (UNCAUGHT_EXCEPTION): Without reason

- error: Cannot read property 'val' of null

- error: Type Cannot read property 'val' of null at fn (/opt/iobroker/node_modules/iobroker.spotify-premium/main.js:1256:31) at Array.map (<anonymous>) at refreshDeviceList (/opt/iobroker/node_modules/iobroker.spotify-premium/main.js:1262:29) at /opt/iobroker/node_modules/iobroker.spotify-premium/main.js:545:33

- error: unhandled promise rejection: Cannot read property 'val' of null

- error: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

**Comment by GermanBluefox** [comment]
PLease test 1.1.4

**Comment by jlssmt** [comment]
first test seems working
thanks ;-)

**Comment by michipi85** [comment]
Perfect. Tried all functions without error.
thanks :D

**Comment by cavernerg** [comment]
Not sure - still got some warns. I'll take a closer look later

**Comment by cavernerg** [comment]
Still got these old warns: 

`<html><body>


spotify-premium.0 | 2021-11-19 06:51:21.918 | info | (10623) State value to set for  "spotify-premium.0.player.playlist.tracksTotal" has to be type "string"  but received type "number"
-- | -- | -- | --
spotify-premium.0 | 2021-11-19 06:49:44.912 | warn | (10623) error on load tracks: 504
spotify-premium.0 | 2021-11-19 06:49:44.912 | warn | at processTicksAndRejections (internal/process/task_queues.js:97:5)
spotify-premium.0 | 2021-11-19 06:49:44.912 | warn | at runMicrotasks (<anonymous>)
spotify-premium.0 | 2021-11-19 06:49:44.912 | warn | at /opt/iobroker/node_modules/iobroker.spotify-premium/main.js:315:38
spotify-premium.0 | 2021-11-19 06:49:44.912 | warn | (10623) Error
spotify-premium.0 | 2021-11-19 06:49:44.912 | warn | at /opt/iobroker/node_modules/iobroker.spotify-premium/main.js:849:25
spotify-premium.0 | 2021-11-19 06:49:44.912 | warn | at getPlaylistTracks (/opt/iobroker/node_modules/iobroker.spotify-premium/main.js:972:12)
spotify-premium.0 | 2021-11-19 06:49:44.912 | warn | at sendRequest (/opt/iobroker/node_modules/iobroker.spotify-premium/main.js:212:21)
spotify-premium.0 | 2021-11-19 06:49:44.912 | warn | (10623) Error
spotify-premium.0 | 2021-11-19 06:49:44.911 | warn | (10623) http request error not handled, please debug
spotify-premium.0 | 2021-11-19 06:34:45.082 | warn | (10623) error on load tracks: 504
spotify-premium.0 | 2021-11-19 06:34:45.082 | warn | at processTicksAndRejections (internal/process/task_queues.js:97:5)
spotify-premium.0 | 2021-11-19 06:34:45.082 | warn | at runMicrotasks (<anonymous>)
spotify-premium.0 | 2021-11-19 06:34:45.082 | warn | at /opt/iobroker/node_modules/iobroker.spotify-premium/main.js:315:38
spotify-premium.0 | 2021-11-19 06:34:45.082 | warn | (10623) Error
spotify-premium.0 | 2021-11-19 06:34:45.082 | warn | at /opt/iobroker/node_modules/iobroker.spotify-premium/main.js:849:25
spotify-premium.0 | 2021-11-19 06:34:45.082 | warn | at getPlaylistTracks (/opt/iobroker/node_modules/iobroker.spotify-premium/main.js:972:12)
spotify-premium.0 | 2021-11-19 06:34:45.082 | warn | at sendRequest (/opt/iobroker/node_modules/iobroker.spotify-premium/main.js:212:21)
spotify-premium.0 | 2021-11-19 06:34:45.082 | warn | (10623) Error
spotify-premium.0 | 2021-11-19 06:34:45.082 | warn | (10623) http request error not handled, please debug


</body>
</html>`

**Comment by jlssmt** [comment]
@cavernerg 
IMHO:
504 is a gateway error. So the adapter can't do anything I would say.
504 is missing in the adapters switch case ([main.js line 289](https://github.com/iobroker-community-adapters/ioBroker.spotify-premium/blob/7bfa428be920441380aecfaacb0963814e062fda/main.js#L289)), so it falls to default case, that's why you get such a long error trace.

I'm btw not receiving this error on 1.1.4 
Do you get this error over the whole day? 

If the adapter works as it should, you can ignore the error. It's just a cosmetic thing.

**Comment by Spremse** [comment]
Hello jlssmt,
it looks very good! No error messages in the log, the ioBrokier frontend is running again.
Thank you very much and greetings,
Bernd

**Comment by michipi85** [comment]
@cavernerg 
i only get the error when the device is not active. Have you checked this? 
![grafik](https://user-images.githubusercontent.com/60364178/142615629-19f7680d-70ac-4fb8-bdb0-f55946c143d8.png)

**Comment by cavernerg** [comment]
@jlssmt : yes it's whole day long. 

@michipi85 : I got some SoundtouchDevices, which come and go ;-) But at the moment all devices are available (because I activated the delete-unavaible-devices option).
