### ISSUE TITLE
Expected "object", received "string"

### ISSUE THREAD

**Issue by duczz** [iobroker-community-adapters/ioBroker.spotify-premium#129]
![image](https://user-images.githubusercontent.com/25475385/157509234-9f5fa4d1-7637-47e4-bf04-a041c6347320.png)
![image](https://user-images.githubusercontent.com/25475385/157514219-a8e0ab94-9f4d-4551-80d3-4ea2e60df222.png)

**Comment by FredF63** [comment]
@GermanBluefox 
Same here, adapter Version 1.1.4, all playlist got this warning

> 2022-04-16 17:42:27.807 - warn: spotify-premium.0 (128596) Object spotify-premium.0.playlists.xxxxxxx.trackList is invalid: obj.common.states has an invalid type! Expected "object", received "string"
--
2022-04-16 17:42:27.807 - warn: spotify-premium.0 (128596) This object will not be created in future versions. Please report this to the developer.

**Comment by guthubps1304** [comment]
same here

**Comment by trackersos** [comment]
same here, any news or workarounds?

**Comment by Apollon77** [comment]
Pleasw delete the objects and let adapte recreate them

**Comment by Apollon77** [comment]
Can someone please show me the content of that tracklist object?

**Comment by Apollon77** [comment]
ok, i tried to fix it ... try GitHub pelase

**Comment by guthubps1304** [comment]
here is an example of an object that ist in the logs
{
  "_id": "spotify-premium.0.player.repeat",
  "type": "state",
  "common": {
    "role": "value",
    "name": "repeat mode",
    "type": "string",
    "read": true,
    "write": true,
    "states": "{\"off\": \"no repeat\",\"context\": \"context, e.g. playlist\",\"track\": \"one track\"}",
    "icon": "icons/repeat_black.png"
  },
  "native": {},
  "from": "system.adapter.spotify-premium.0",
  "user": "system.user.admin",
  "ts": 1651662459027,
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}

**Comment by guthubps1304** [comment]
just tried to install from Github - will report my findings here

**Comment by guthubps1304** [comment]
deleted allobjects and restarted Spotiy-Premium - currently I do not get any errors :-)) I will monitor the logs and will provide an update tomorrow - thanks !!!

**Comment by FredF63** [comment]
with Github update tracklist error is gone, but still errors for states has invalid type:

>2022-05-04 14:17:38.917 - warn: spotify-premium.0 (2315384) Object spotify-premium.0.player.repeat is invalid: obj.common.states has an invalid type! Expected "object", received "string"
2022-05-04 14:17:38.918 - warn: spotify-premium.0 (2315384) This object will not be created in future versions. Please report this to the developer.
2022-05-04 14:17:38.976 - warn: spotify-premium.0 (2315384) Object spotify-premium.0.player.shuffle is invalid: obj.common.states has an invalid type! Expected "object", received "string"
2022-05-04 14:17:38.976 - warn: spotify-premium.0 (2315384) This object will not be created in future versions. Please report this to the developer.
2022-05-04 14:17:39.066 - warn: spotify-premium.0 (2315384) Object spotify-premium.0.player.type is invalid: obj.common.states has an invalid type! Expected "object", received "string"
2022-05-04 14:17:39.066 - warn: spotify-premium.0 (2315384) This object will not be created in future versions. Please report this to the developer.
2022-05-04 14:17:39.191 - warn: spotify-premium.0 (2315384) Object spotify-premium.0.player.device.type is invalid: obj.common.states has an invalid type! Expected "object", received "string"
2022-05-04 14:17:39.191 - warn: spotify-premium.0 (2315384) This object will not be created in future versions. Please report this to the developer.

deleting all objects and restarting does not help.

**Comment by guthubps1304** [comment]
I did receive an error after starting Spotify on my Smartphone:
State "spotify-premium.0.playlists.spotify-37i9dQZF1DX8kI525v95Yu.trackList" has no existing object, this might lead to an error in future versions.

Content of object:
{
  "_id": "spotify-premium.0.player.playlist.trackList",
  "type": "state",
  "common": {
    "name": "Tracks of the playlist saved in common part. Change this value to a track position number to start this playlist with this track.",
    "type": "mixed",
    "role": "value",
    "states": "0:With Or Without You - Remastered - U2;1:One - Remastered 2018 - U2;2:I Still Haven't Found What I'm Looking For - U2;3:Beautiful Day - U2;4:Pride (In The Name Of Love) - Remastered 2009 - U2;5:Where The Streets Have No Name - U2;6:New Year's Day - Single Edit - Remastered - U2;7:Vertigo - U2;8:Mysterious Ways - Remastered 2018 - U2;9:Stuck In A Moment You Can't Get Out Of - U2;10:Sunday Bloody Sunday - Remastered 2008 - U2;11:All I Want Is You - U2;12:Sweetest Thing - U2;13:Stay (Faraway, So Close!) - U2;14:Your Song Saved My Life - From Sing 2 - U2;15:Elevation - U2;16:Every Breaking Wave - U2;17:Bad - U2;18:Angel Of Harlem - U2;19:Desire - U2;20:Until The End Of The World - Remastered 2018 - U2;21:City Of Blinding Lights - U2;22:Walk On - U2;23:I Will Follow - Remastered 2008 - U2;24:You’re The Best Thing About Me - U2;25:Summer Of Love - U2;26:The Unforgettable Fire - Remastered 2009 - U2;27:Stuck In A Moment You Can't Get Out Of - Acoustic Version / Remastered 2020 - U2;28:Ahimsa - U2, A.R. Rahman;29:Ultra Violet (Light My Way) - Remastered 2018 - U2;30:Even Better Than The Real Thing - Trance Mix / Remastered 2021 - U2, Paul Oakenfold;31:In God's Country - U2;32:Sometimes You Can't Make It On Your Own - U2;33:Song For Someone - U2;34:The Saints Are Coming - U2, Green Day;35:Magnificent - U2;36:The Miracle (Of Joey Ramone) - U2;37:Staring At The Sun - U2;38:Get Out Of Your Own Way - U2;39:In A Little While - U2;40:I'll Go Crazy If I Don't Go Crazy Tonight - U2;41:Bullet The Blue Sky - U2;42:The Ground Beneath Her Feet - U2;43:Gone - U2;44:Love Is All We Have Left - U2;45:Love Is Bigger Than Anything In Its Way - U2;46:The Little Things That Give You Away - Recorded at Neptune Valley, LA - U2;47:The Blackout - U2;48:If God Will Send His Angels - U2;49:13 (There is A Light) - U2;50:The Showman (Little More Better) - U2;51:Lights Of Home - U2;52:Landlady - U2;53:Red Flag Day - U2;54:Please - U2;55:Book Of Your Heart - U2;56:If You Wear That Velvet Dress - U2;57:Ordinary Love - U2;58:Until The End Of The World - U2",
    "read": true,
    "write": true
  },
  "native": {},
  "from": "system.adapter.spotify-premium.0",
  "user": "system.user.admin",
  "ts": 1651663315673,
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}

**Comment by Apollon77** [comment]
Thank you, this object helps a lot, fix coming later today

**Comment by Apollon77** [comment]
Please try GitHub version regarding the tracklist "error

**Comment by guthubps1304** [comment]
is it sufficient to copy the code url here and install in iobroker from that URL - did you already update the code?

**Comment by Apollon77** [comment]
best go Admin, enable expert mode, click the HitHub/Custom install icon and choose the adapter from the list on tab "From GitHub". Yes is already updated

**Comment by guthubps1304** [comment]
I am running version 1.1.9 - ist his the expected one?

**Comment by guthubps1304** [comment]
still error messages:


spotify-premium.0 | 2022-05-05 08:47:45.798 | warn | Object spotify-premium.0.playlists.spotify-37i9dQZF1DX6VdMW310YC7.trackList is invalid: obj.common.states has an invalid type! Expected "object", received "string"
this object is empty !!!

spotify-premium.0 | 2022-05-05 08:47:36.637 | warn | Object spotify-premium.0.player.device.type is invalid: obj.common.states has an invalid type! Expected "object", received "string"
this object is empty !!!

spotify-premium.0 | 2022-05-05 08:47:36.362 | warn | Object spotify-premium.0.player.type is invalid: obj.common.states has an invalid type! Expected "object", received "string"
this object is empty !!!
spotify-premium.0 | 2022-05-05 08:47:36.181 | warn | Object spotify-premium.0.player.shuffle is invalid: obj.common.states has an invalid type! Expected "object", received "string"

content of the object: Off(off)

**Comment by guthubps1304** [comment]
object with error: spotify-premium.0.playlists.spotify-37i9dQZF1DX6xOPeSOGone.trackList

trackless field is empty
![image](https://user-images.githubusercontent.com/79707394/166920520-04efcbe2-c6ab-48a4-916b-b9564e13cef7.png)

example object data:
{
  "type": "state",
  "common": {
    "name": "Tracks of the playlist saved in common part. Change this value to a track position number to start this playlist with this track. First track is 0",
    "type": "mixed",
    "role": "value",
    "states": "0:Landslide - Fleetwood Mac;1:One - U2;2:The Living Years - Mike & The Mechanics;3:Keep on Loving You - REO Speedwagon;4:Purple Rain - Prince;5:Kayleigh - Marillion;6:Rosanna - TOTO;7:Alone - Heart;8:Blaze Of Glory - Bon Jovi;9:I Still Haven't Found What I'm Looking For - Remastered 2007 - U2;10:Black Velvet - Alannah Myles;11:Alive And Kicking - Simple Minds;12:Cats In The Cradle - Ugly Kid Joe;13:Broken Wings - Mr. Mister;14:Human Touch - Bruce Springsteen;15:All I Wanna Do Is Make Love To You - Heart;16:Walking in Memphis - Marc Cohn;17:Janie's Got A Gun - Aerosmith;18:Runaway Train - Soul Asylum;19:The Way It Is - Bruce Hornsby, The Range;20:Amanda - Boston;21:Give A Little Bit - Supertramp;22:Every Rose Has Its Thorn - Remastered 2003 - Poison;23:Urgent - 2008 Remaster - Foreigner;24:Rough Boy - ZZ Top;25:Can't Fight This Feeling - REO Speedwagon;26:New York Minute - Don Henley;27:Heaven For Everyone - Remastered 2011 - Queen;28:To Be With You - 2010 Remastered Version - Mr. Big;29:Stop Loving You - TOTO;30:Free Fallin' - Tom Petty;31:Baker Street - Gerry Rafferty;32:Ride Like the Wind - Christopher Cross;33:All For Love - From \"The Three Musketeers\" Soundtrack - Bryan Adams, Sting, Rod Stewart;34:Don't Stop Believin' - Journey;35:With Or Without You - Remastered - U2;36:The River - Bruce Springsteen;37:Wanted Dead Or Alive - Bon Jovi;38:My Father's Eyes - 2015 Remaster - Eric Clapton;39:Let Your Love Flow - The Bellamy Brothers;40:Romeo And Juliet - Dire Straits;41:Everybody Hurts - R.E.M.;42:Streets of Philadelphia - Single Edit - Bruce Springsteen;43:Bed Of Roses - Bon Jovi;44:The End Of The Innocence - Don Henley;45:Mmm Mmm Mmm Mmm - Crash Test Dummies;46:This Is Not America (with The Pat Metheny Group) - 2014 Remastered Version - David Bowie, Pat Metheny Group;47:Weather With You - Crowded House;48:Livin' Thing - Electric Light Orchestra;49:I'm On Fire - Bruce Springsteen;50:Drive - The Cars;51:Drive - R.E.M.;52:Never Tear Us Apart - INXS;53:Africa - TOTO;54:Hungry Eyes - From \"Dirty Dancing\" Soundtrack - Eric Carmen;55:Just the Way It Is, Baby - The Rembrandts;56:My Hometown - Bruce Springsteen;57:Ordinary World - Duran Duran;58:Mama, I'm Coming Home - Ozzy Osbourne;59:Love Bites - Remastered 2017 - Def Leppard;60:Is This Love - 2018 Remaster - Whitesnake;61:Lyin' Eyes - 2013 Remaster - Eagles;62:Thought I'd Died And Gone To Heaven - Bryan Adams;63:Handbags And Gladrags - Stereophonics;64:Glory of Love - Peter Cetera;65:Love Hurts - Nazareth;66:Wind Of Change - Scorpions;67:Losing My Religion - R.E.M.;68:Don't Dream It's Over - Crowded House;69:When Love & Hate Collide - Def Leppard;70:Still Got The Blues - Gary Moore;71:Just Around the Corner - Cock Robin;72:Easy - Faith No More;73:Lover of Mine - Alannah Myles;74:November Rain - Guns N' Roses;75:Hotel California - 2013 Remaster - Eagles;76:Angie - Remastered 2009 - The Rolling Stones;77:Missing You - John Waite;78:Sailing - 2008 Remaster - Rod Stewart;79:Sara - Fleetwood Mac;80:Wonderful Tonight - Eric Clapton;81:New Kid in Town - 2013 Remaster - Eagles;82:I Remember You - Skid Row;83:The Flame - Cheap Trick;84:My Life - Billy Joel;85:Maneater - Daryl Hall & John Oates;86:All Out of Love - Air Supply;87:Hysteria - Remastered 2017 - Def Leppard;88:When the Children Cry - White Lion;89:Hold On - Jamie Walters;90:18 and Life - Skid Row;91:I Don't Want to Miss a Thing - From \"Armageddon\" Soundtrack - Aerosmith;92:(Everything I Do) I Do It For You - Bryan Adams;93:Rocket Man (I Think It's Going To Be A Long Long Time) - Elton John;94:If You Leave Me Now - Chicago;95:When I Was a Boy - Electric Light Orchestra;96:What's Up? - 4 Non Blondes;97:How Do You Talk To An Angel? - The Heights;98:Heaven - Bryan Adams;99:Tears in Heaven - Acoustic Live at MTV Unplugged, Bray Film Studios, Windsor, England, UK, 1/16/1992 2013 Remaster - Eric Clapton;100:Every Breath You Take - Remastered 2003 - The Police;101:Have You Ever Seen The Rain - Creedence Clearwater Revival;102:Carrie - Europe;103:Stairway to Heaven - 1990 Remaster - Led Zeppelin;104:Dust in the Wind - Kansas;105:Hard Habit to Break - 2006 Remaster - Chicago;106:Secret Garden - Bruce Springsteen;107:Send Me An Angel - Scorpions;108:Knockin' On Heaven's Door - Bob Dylan;109:'74-'75 - The Connells;110:Woman In Chains - Tears For Fears, Oleta Adams;111:Patience - Guns N' Roses;112:Tiny Dancer - Elton John;113:You're the Inspiration - 2009 Remaster - Chicago;114:All Right - Christopher Cross;115:Heart of Gold - 2009 Remaster - Neil Young;116:What a Fool Believes - The Doobie Brothers;117:Dreadlock Holiday - 10cc;118:Faithfully - Journey;119:Stuck In The Middle With You - Stealers Wheel;120:Hard to Say I'm Sorry / Get Away - 2006 Remaster - Chicago;121:Do I Have To Say The Words? - Bryan Adams;122:Wild Horses - 2009 Mix - The Rolling Stones;123:Everywhere - Fleetwood Mac;124:Miracle of Love - Eurythmics;125:Change the World - 2015 Remaster - Eric Clapton;126:Wish You Were Here - 2011 Remaster - Pink Floyd;127:Open Arms - Journey;128:Wild World - 2009 Remastered Version - Mr. Big;129:Hallelujah - Jeff Buckley;130:Wild Horses - The Rolling Stones;131:Don't Talk to Strangers - Rick Springfield;132:The Sound of Silence - Disturbed;133:I Surrender - Saybia;134:A Horse with No Name - America, George Martin;135:Always - Bon Jovi;136:Breakfast In America - Remastered - Supertramp;137:Good Riddance (Time of Your Life) - Green Day;138:Your Latest Trick - Dire Straits;139:One of These Nights - 2013 Remaster - Eagles;140:Amazing - Aerosmith;141:The Drugs Don't Work - The Verve;142:Please Forgive Me - Bryan Adams;143:Under the Bridge - Red Hot Chili Peppers;144:The Sound of Silence - Acoustic Version - Simon & Garfunkel;145:Walk On the Ocean - Toad The Wet Sprocket;146:I'm Not In Love - 10cc;147:Disarm - Remastered - The Smashing Pumpkins;148:Behind Blue Eyes - Limp Bizkit;149:You Get What You Give - New Radicals",
    "read": true,
    "write": true
  },
  "native": {},
  "from": "system.adapter.spotify-premium.0",
  "user": "system.user.admin",
  "ts": 1651752484064,
  "_id": "spotify-premium.0.playlists.spotify-37i9dQZF1DX6xOPeSOGone.trackList",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}

**Comment by Apollon77** [comment]
Bitte mal mit eingeschaltetem Debug log (also Instanzen - expertenmodus - loglevel ändern) ein Debug log zeigen. Ich kapiers nicht das das Objekt so aussieht wenn die GitHub version genutzt wird!! (Und der GitHub install hat geklappt????)

**Comment by guthubps1304** [comment]
Debug Level eingestellt:


2022-05-07 09:20:38.784 | warn | This object will not be created in future versions. Please report this to the developer.
-- | -- | --
spotify-premium.0 | 2022-05-07 09:20:38.783 | warn | Object spotify-premium.0.playlists.spotify-37i9dQZF1DX6VdMW310YC7.trackList is invalid: obj.common.states has an invalid type! Expected "object", received "string"
spotify-premium.0 | 2022-05-07 09:20:32.319 | info | State value to set for "spotify-premium.0.player.playlist.tracksTotal" has to be type "string" but received type "number"
spotify-premium.0 | 2022-05-07 09:20:30.938 | info | starting. Version 1.1.9 (non-npm: iobroker-community-adapters/ioBroker.spotify-premium#b41026cc1e874e5762bef3d6cfc81bf4006724cc) in /opt/iobroker/node_modules/iobroker.spotify-premium, node: v14.19.1, js-controller: 4.0.23

**Comment by guthubps1304** [comment]
diese Fehler kommen ständig:


This object will not be created in future versions. Please report this to the developer.
--
spotify-premium.0 | 2022-05-07 09:22:00.529 | warn | Object spotify-premium.0.playlists.spotify-37i9dQZF1DXccljMjoDjBT.trackList is invalid: obj.common.states has an invalid type! Expected "object", received "string"

**Comment by guthubps1304** [comment]
letzter Eintrag im Log nach Neustart der Instanz:


spotify-premium.0 | 2022-05-07 09:39:38.696 | error | playlist error empty playlist name
spotify-premium.0 | 2022-05-07 09:39:38.694 | warn | empty playlist name
spotify-premium.0 | 2022-05-07 09:39:35.652 | warn | This object will not be created in future versions. Please report this to the developer.
spotify-premium.0 | 2022-05-07 09:39:35.652 | warn | Object spotify-premium.0.playlists.spotify-37i9dQZF1DX82pCGH5USnM.trackList is invalid: obj.common.states has an invalid type! Expected "object", received "string"

**Comment by guthubps1304** [comment]
Beobachtung: der Adapter liest wohl alle meine Playlists ein, die ich in meinem Account habe. Das object tracklist ist dann leer; 
![image](https://user-images.githubusercontent.com/79707394/167245870-75bee7dc-4114-4553-a836-00d2d01dd9aa.png).

die Playlists verschwinden dann alle aus der Object Übersicht:
![image](https://user-images.githubusercontent.com/79707394/167245972-3974dc9f-790c-4c00-9fc5-d194fa3564e7.png)

**Comment by Apollon77** [comment]
> Debug Level eingestellt

Wirklich? Dann verstehe ich nicht das keinerlei Debug Meldungen im Log sind.

Nur nochmal zur sicherheit: Admin - Instanzen - Expertenmodus - Instanz aufklappen. Dort Logleel von info auf debug stellen.

**Comment by guthubps1304** [comment]
Sorry, nur im Tab Logs auf Debug gestellt, jetzt auch im Adapter:

> 

spotify-premium.0 | 2022-05-08 09:01:09.226 | warn | This object will not be created in future versions. Please report this to the developer.
-- | -- | -- | --
spotify-premium.0 | 2022-05-08 09:01:09.226 | warn | Object spotify-premium.0.playlists.1166570638-7H5C87iGpl6IpwFbq49PIc.trackList is invalid: obj.common.states has an invalid type! Expected "object", received "string"
spotify-premium.0 | 2022-05-08 09:01:09.225 | debug | save object: playlists.1166570638-7H5C87iGpl6IpwFbq49PIc.trackList -> {"type":"state","common":{"name":"Tracks of the playlist saved in common part. Change this value to a track position number to start this playlist with this track. First track is 0","type":"mixed","role":"value","states":"0:Schiller - Live - Schiller;1:Come to Me - Radio Edit - Lily & Madeleine, Ofenbach;2:Go Fuck Yourself - Two Feet;3:Keep the Streets Empty For Me - Fever Ray;4:Return to Tunguska ft. Shpongle & Dave Gilmour - Alan Parsons;5:Invisible Sun - The Prodigy;6:Before - Neelix Well Done Remix - Vök, Neelix;7:Sunlight (feat. Years and Years) - Darius Remix - The Magician, Years & Years, Darius;8:Hymn Revolution - Thomas Schumacher;9:Waldbrand - Chris Avedon & Kevin Neon Remix - Madeline Juno, Chris Avedon, Kevin Neon;10:Prodigium - Beave, LexBlaze;11:My Name Is Human - Highly Suspect;12:Speed of Soul - Ghost Rider;13:Leave a Light On - AlunaGeorge Remix - Tom Walker, AlunaGeorge;14:Be Focused - Ghost Rider;15:Tripical Moon - Querox, Phaxe;16:Bayaka - Berg;17:In The Air Tonight - 2015 Remastered - Phil Collins;18:When Doves Cry - The Voice Australia 2018 Performance / Live - Sam Perry;19:Purple Rain - Prince;20:ORAS - SARO;21:Friendships - Pascal Letoublon;22:Enjoy the Silence - Ecstatic Dub - Depeche Mode, Francois Kevorkian;23:Zombie - Acoustic Version - Clödie;24:The Spirit (Single Mix) - Pinball;25:Drüg - Lucky Luke, Emie;26:Make Ü Mine - Lucky Luke, Austuzhe;27:Never Be Like You - Flume, kai;28:Venom - Dave202;29:Great Spirit (ASOT 821) - Armin van Buuren, Vini Vici, Hilight Tribe;30:Free Tibet - Vini Vici Remix - Hilight Tribe, Vini Vici;31:In My Mind - Remix - MoshTekk;32:Applaus - Piano Sessions - LEA;33:Glad You Came - VIZE;34:Anybody - Radio Edit - Tomcraft, Gil Ofarim;35:bury a friend - Billie Eilish;36:Hard Like a Drum - Rebugs Remix - Naturalize, Rebugs;37:You - Extended Mix - Neelix;38:Fludora - Pretty Pink;39:I Be As I Am - Original Mix - Pribe;40:Hurricane - Sick Cycle Remix - MS MR;41:Wicked Game - Chris Isaak;42:Light - Mixed - Jerome;43:All In My Head - Jason Lemm;44:Adventure - Axline;45:Silence - PaulWetz;46:When I'm Small - Phantogram;47:Dark Sun - KELTEK;48:Memory Gospel - Moby;49:Facing Fears (feat. Celica Soldream) - Iván Torrent, Celica Soldream;50:Moon Rises - Original MIx - Montez;51:In Between - Schiller, Jan Blomqvist;52:Quick Musical Doodles - Two Feet;53:Twerk It - AFISHAL;54:L'amour Toujours (Anson Bootleg) - Anson;55:Tell Me A Lie - Jason Lemm;56:Escape - Liquexx, Mairex;57:The Moments I'm Missing (feat. Nina Nesbitt) - Ranji, WHITENO1SE, Nina Nesbitt;58:Fume - Maxun;59:Odeyowa - Liquexx, Mairex;60:Wicked Game - Ursine Vulpine, Annaca;61:Shadows - Neelix;62:you broke me first - Tate McRae;63:Morning Traffic - Electrix;64:Changes - Fullife;65:Fire - Deva Mahal;66:Alone In The Dark - Pribe;67:When Music Matters - Extended Mix - Friends Of Mayday;68:Silent Voice - Adan Hüjens, Von DC;69:Thank You - Original - Jesus Fellowship;70:You're Not Alone - 2Elements, Nazzereene;71:Escape - Nath Jennings;72:A Million On My Soul (Remix) - Moses, EMR3YGUL, Alexiane;73:fühlen - Alfred Heinrichs, Lukas Potempa;74:Shake It Out - MTV Unplugged, 2012 - Florence + The Machine;75:Intense - Dantec;76:Disfruto - Audioiko Remix - Carla Morrison, Audioiko;77:Frozen - Nivlem","read":true,"write":true},"native":{}}

**Comment by duczz** [comment]
![Screenshot_20220512-074220_Chrome](https://user-images.githubusercontent.com/25475385/168000328-a9454aa7-cdf5-4ebf-aaa1-366d04b6558e.jpg)

**Comment by guthubps1304** [comment]
> Ok, honestly ... I'm unsure if you really installed the GitHub version because your log do not look like that case ... or I miss a place. So to make sure I will release the other fixes and then you check the official update again and provide a new log that shows the new version :-)

sorry für die Umstände, so installiere ich:
![image](https://user-images.githubusercontent.com/79707394/168005262-b07bc429-ce54-4be5-b103-66278037a3c9.png)

Was ist der richtige Weg, um deine neuste Version zu erhalten?
Gruß Peter

**Comment by Apollon77** [comment]
Meine neueste Version ist ganz normal im beta Repo ... Weiterhin sind GitHub updates viel einfacher über den "von GitHub" Tab zu bekommen ... :-))

Benutzerdefiniert braucht man eigentlich nur wenn der Adapter nicht im Repository ist

**Comment by guthubps1304** [comment]
Okay also einfach den Adapter in der Mitte "Github" suchen und installieren, richtig?
![image](https://user-images.githubusercontent.com/79707394/168011562-9e76ed1c-a1fe-46b4-b8c0-83c12492f588.png)

habe mal alles gelöscht und werde nochmal neu installieren.

**Comment by guthubps1304** [comment]
so jetzt habe ich wohl die aktuelle Beta:

2022-05-12 09:15:38.810 | info | starting. Version 1.2.0 in /opt/iobroker/node_modules/iobroker.spotify-premium, node: v14.19.2, js-controller: 4.0.23

beim Start wurden alle Playlists eingelesen und dann wieder alle gelöscht - ist das gewollt?

Das kommt jetzt als Warnung:


2022-05-12 09:20:02.034 | error | playlist error empty playlist name
-- | -- | --
spotify-premium.0 | 2022-05-12 09:20:02.033 | warn | empty playlist name
spotify-premium.0 | 2022-05-12 09:15:38.753 | warn | This object will not be created in future versions. Please report this to the developer.
spotify-premium.0 | 2022-05-12 09:15:38.752 | warn | Object spotify-premium.0.player.device.type is invalid: obj.common.states has an invalid type! Expected "object", received "string"
spotify-premium.0 | 2022-05-12 09:15:38.522 | warn | This object will not be created in future versions. Please report this to the developer.
spotify-premium.0 | 2022-05-12 09:15:38.522 | warn | Object spotify-premium.0.player.type is invalid: obj.common.states has an invalid type! Expected "object", received "string"
spotify-premium.0 | 2022-05-12 09:15:38.374 | warn | This object will not be created in future versions. Please report this to the developer.
spotify-premium.0 | 2022-05-12 09:15:38.373 | warn | Object spotify-premium.0.player.shuffle is invalid: obj.common.states has an invalid type! Expected "object", received "string"
spotify-premium.0 | 2022-05-12 09:15:38.286 | warn | This object will not be created in future versions. Please report this to the developer.
spotify-premium.0 | 2022-05-12 09:15:38.285 | warn | Object spotify-premium.0.player.repeat is invalid: obj.common.states has an invalid type! Expected "object", received "string"

**Comment by Apollon77** [comment]
Ok, schaue gern danach. Sind ja aber jetzt andere Meldungen :-)

**Comment by guthubps1304** [comment]
genau sieht jetzt aber schon viel besser aus - danke für deine Geduld :-))

**Comment by guthubps1304** [comment]
das ist der einzigste Ehler der noch im Log auftaucht:

2022-05-12 14:18:12.665 | error | playlist error empty playlist name
spotify-premium.0 | 2022-05-12 14:18:12.664 | warn | empty playlist name
