### ISSUE TITLE
Error request 404

### ISSUE THREAD

**Issue by Stefan-CH-87** [iobroker-community-adapters/ioBroker.spotify-premium#133]
Ich habe gestern zum 1. Mal den Adapter installiert und erhalte des öfteren den Fehler:
erron in request: 404

Woran liegt das?
![grafik](https://user-images.githubusercontent.com/100514436/163841189-4312ee8e-4d21-44f7-9fb9-a611965a0389.png)

**Comment by duczz** [comment]
Der Fehler wurde bereits mit nem Pull gefixt.
@GermanBluefox könntest du es ins latest pushen?
