### ISSUE TITLE
system.adapter.spotify-premium.0 terminated

### ISSUE THREAD

**Issue by BatmanN8** [iobroker-community-adapters/ioBroker.spotify-premium#143]
* The adapter crashed. 
* I can't see a pattern

Adapter 1.2.2
Nodejs 14.18.1
Host 4.0.23
Raspberry Pi4

![Screenshot 2022-06-25 130528](https://user-images.githubusercontent.com/96910907/175771000-9fafaa6f-d708-4819-bcd4-cdc80fb4bb1a.jpg)

**Comment by mehlaug3** [comment]
Same here.
Adapter 1.2.1

PlatformBetriebssystem:linux
Architektur:x64
CPUs:2
Geschwindigkeit:2001 MHz
Modell:Intel(R) Celeron(R) J4025 CPU @ 2.00GHz
RAM:9.5 GB
System-Betriebszeit:1 T. 16:29:05
Node.js:v16.16.0
time:1661957315333
timeOffset:-120
Adapter-Anzahl:431
NPM:8.11.0
Datenträgergröße:5361.0 GB
Freier Festplattenspeicher:4415.7 GB
Betriebszeit:1 T. 16:25:10
Aktive Instanzen:28
Pfad:/opt/iobroker/
aktiv:true
_nodeCurrent:16.16.0
_nodeNewest:16.17.0
_nodeNewestNext:16.17.0
_npmCurrent:8.11.0
_npmNewest:8.18.0
_npmNewestNext:8.18.0

**Comment by Tetraden** [comment]
Same here, but at least I have stack traces in my log.

![image](https://user-images.githubusercontent.com/22071623/197463970-35f3729b-0b9a-4d25-95e6-a14fde544afb.png)

**Comment by Vumer4** [comment]
here with me
`host.iobroker 2022-11-19 13:02:24.813	error	instance system.adapter.spotify-premium.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
host.iobroker 2022-11-19 13:02:24.812	error	Caught by controller[8]: 503
host.iobroker 2022-11-19 13:02:24.812	error	Caught by controller[7]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
host.iobroker 2022-11-19 13:02:24.812	error	Caught by controller[6]: at processTicksAndRejections (node:internal/process/task_queues:96:5)
host.iobroker 2022-11-19 13:02:24.812	error	Caught by controller[6]: at runMicrotasks (<anonymous>)
host.iobroker 2022-11-19 13:02:24.812	error	Caught by controller[6]: at /opt/iobroker/node_modules/iobroker.spotify-premium/main.js:973:21
host.iobroker 2022-11-19 13:02:24.812	error	Caught by controller[6]: at createOrDefault (/opt/iobroker/node_modules/iobroker.spotify-premium/main.js:387:13)
host.iobroker 2022-11-19 13:02:24.812	error	Caught by controller[6]: at loadOrDefault (/opt/iobroker/node_modules/iobroker.spotify-premium/main.js:373:13)
host.iobroker 2022-11-19 13:02:24.812	error	Caught by controller[6]: at eval (eval at loadOrDefault (/opt/iobroker/node_modules/iobroker.spotify-premium/main.js:372:19), <anonymous>:3:12)
host.iobroker 2022-11-19 13:02:24.812	error	Caught by controller[6]: TypeError: Cannot read properties of undefined (reading 'songs')
host.iobroker 2022-11-19 13:02:24.812	error	Caught by controller[5]: at processTicksAndRejections (node:internal/process/task_queues:96:5)
host.iobroker 2022-11-19 13:02:24.812	error	Caught by controller[5]: at runMicrotasks (<anonymous>)
host.iobroker 2022-11-19 13:02:24.812	error	Caught by controller[5]: at /opt/iobroker/node_modules/iobroker.spotify-premium/main.js:970:21
host.iobroker 2022-11-19 13:02:24.812	error	Caught by controller[5]: at createOrDefault (/opt/iobroker/node_modules/iobroker.spotify-premium/main.js:387:13)
host.iobroker 2022-11-19 13:02:24.812	error	Caught by controller[5]: at loadOrDefault (/opt/iobroker/node_modules/iobroker.spotify-premium/main.js:373:13)
host.iobroker 2022-11-19 13:02:24.812	error	Caught by controller[5]: at eval (eval at loadOrDefault (/opt/iobroker/node_modules/iobroker.spotify-premium/main.js:372:19), <anonymous>:3:12)
host.iobroker 2022-11-19 13:02:24.812	error	Caught by controller[5]: TypeError: Cannot read properties of undefined (reading 'trackIds')
host.iobroker 2022-11-19 13:02:24.812	error	Caught by controller[4]: at processTicksAndRejections (node:internal/process/task_queues:96:5)
host.iobroker 2022-11-19 13:02:24.812	error	Caught by controller[4]: at runMicrotasks (<anonymous>)
host.iobroker 2022-11-19 13:02:24.812	error	Caught by controller[4]: at /opt/iobroker/node_modules/iobroker.spotify-premium/main.js:967:21
host.iobroker 2022-11-19 13:02:24.812	error	Caught by controller[4]: at createOrDefault (/opt/iobroker/node_modules/iobroker.spotify-premium/main.js:387:13)
host.iobroker 2022-11-19 13:02:24.811	error	Caught by controller[4]: at loadOrDefault (/opt/iobroker/node_modules/iobroker.spotify-premium/main.js:373:13)
host.iobroker 2022-11-19 13:02:24.811	error	Caught by controller[4]: at eval (eval at loadOrDefault (/opt/iobroker/node_modules/iobroker.spotify-premium/main.js:372:19), <anonymous>:3:12)
host.iobroker 2022-11-19 13:02:24.811	error	Caught by controller[4]: TypeError: Cannot read properties of undefined (reading 'trackIdMap')
host.iobroker 2022-11-19 13:02:24.811	error	Caught by controller[3]: at processTicksAndRejections (node:internal/process/task_queues:96:5)
host.iobroker 2022-11-19 13:02:24.811	error	Caught by controller[3]: at runMicrotasks (<anonymous>)
host.iobroker 2022-11-19 13:02:24.811	error	Caught by controller[3]: at /opt/iobroker/node_modules/iobroker.spotify-premium/main.js:964:21
host.iobroker 2022-11-19 13:02:24.811	error	Caught by controller[3]: at createOrDefault (/opt/iobroker/node_modules/iobroker.spotify-premium/main.js:387:13)
host.iobroker 2022-11-19 13:02:24.811	error	Caught by controller[3]: at loadOrDefault (/opt/iobroker/node_modules/iobroker.spotify-premium/main.js:373:13)
host.iobroker 2022-11-19 13:02:24.811	error	Caught by controller[3]: at eval (eval at loadOrDefault (/opt/iobroker/node_modules/iobroker.spotify-premium/main.js:372:19), <anonymous>:3:12)
host.iobroker 2022-11-19 13:02:24.811	error	Caught by controller[3]: TypeError: Cannot read properties of undefined (reading 'stateString')
host.iobroker 2022-11-19 13:02:24.811	error	Caught by controller[2]: at processTicksAndRejections (node:internal/process/task_queues:96:5)
host.iobroker 2022-11-19 13:02:24.811	error	Caught by controller[2]: at runMicrotasks (<anonymous>)
host.iobroker 2022-11-19 13:02:24.811	error	Caught by controller[2]: at /opt/iobroker/node_modules/iobroker.spotify-premium/main.js:961:21
host.iobroker 2022-11-19 13:02:24.811	error	Caught by controller[2]: at createOrDefault (/opt/iobroker/node_modules/iobroker.spotify-premium/main.js:387:13)
host.iobroker 2022-11-19 13:02:24.811	error	Caught by controller[2]: at loadOrDefault (/opt/iobroker/node_modules/iobroker.spotify-premium/main.js:373:13)
host.iobroker 2022-11-19 13:02:24.811	error	Caught by controller[2]: at eval (eval at loadOrDefault (/opt/iobroker/node_modules/iobroker.spotify-premium/main.js:372:19), <anonymous>:3:12)
host.iobroker 2022-11-19 13:02:24.811	error	Caught by controller[2]: TypeError: Cannot read properties of undefined (reading 'listString')
host.iobroker 2022-11-19 13:02:24.811	error	Caught by controller[2]: at processTicksAndRejections (node:internal/process/task_queues:96:5)
host.iobroker 2022-11-19 13:02:24.811	error	Caught by controller[2]: at runMicrotasks (<anonymous>)
host.iobroker 2022-11-19 13:02:24.811	error	Caught by controller[2]: at /opt/iobroker/node_modules/iobroker.spotify-premium/main.js:958:21
host.iobroker 2022-11-19 13:02:24.811	error	Caught by controller[2]: at createOrDefault (/opt/iobroker/node_modules/iobroker.spotify-premium/main.js:387:13)
host.iobroker 2022-11-19 13:02:24.810	error	Caught by controller[2]: at loadOrDefault (/opt/iobroker/node_modules/iobroker.spotify-premium/main.js:373:13)
host.iobroker 2022-11-19 13:02:24.810	error	Caught by controller[2]: at eval (eval at loadOrDefault (/opt/iobroker/node_modules/iobroker.spotify-premium/main.js:372:19), <anonymous>:3:12)
host.iobroker 2022-11-19 13:02:24.810	error	Caught by controller[2]: TypeError: Cannot read properties of undefined (reading 'listNumber')
host.iobroker 2022-11-19 13:02:24.810	error	Caught by controller[1]: at processTicksAndRejections (node:internal/process/task_queues:96:5)
host.iobroker 2022-11-19 13:02:24.810	error	Caught by controller[1]: at runMicrotasks (<anonymous>)
host.iobroker 2022-11-19 13:02:24.810	error	Caught by controller[1]: at /opt/iobroker/node_modules/iobroker.spotify-premium/main.js:937:32
host.iobroker 2022-11-19 13:02:24.810	error	Caught by controller[1]: at loadOrDefault (/opt/iobroker/node_modules/iobroker.spotify-premium/main.js:373:13)
host.iobroker 2022-11-19 13:02:24.810	error	Caught by controller[1]: at eval (eval at loadOrDefault (/opt/iobroker/node_modules/iobroker.spotify-premium/main.js:372:19), <anonymous>:3:12)
host.iobroker 2022-11-19 13:02:24.810	error	Caught by controller[1]: TypeError: Cannot read properties of undefined (reading 'stateString')
spotify-premium.0 2022-11-19 13:02:24.099	error	undefined
spotify-premium.0 2022-11-19 13:02:24.099	error	unhandled promise rejection: undefined
spotify-premium.0 2022-11-19 13:02:24.095	error	Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().`
