### ISSUE TITLE
unexpected api response http 503; continue polling

### ISSUE THREAD

**Issue by duczz** [iobroker-community-adapters/ioBroker.spotify-premium#160]
Der Adapter stützt sein ein paar Wochen ständig im loop mit folgendem Fehler ab.

`unexpected api response http 503; continue polling`

@Apollon77 Kannst du da ggf wieder was machen? :)

**Comment by Apollon77** [comment]
So mal eben geraten mit den Infos hier ... nö. 

Mal vllt ein log - ideal debug log - posten was da Problem zeigt? 

Ich habe kein Spotify und meine Glaskugel leider verlegt. Sorry

**Comment by andre-bu** [comment]
Hallo,
hab das gleiche Problem. 
`
2022-12-10 22:04:08.840  - warn: spotify-premium.0 (1394170) unexpected api response http 503; continue polling
2022-12-10 22:04:10.600  - error: spotify-premium.0 (1394170) spotify device polling stopped with error 503`

Nach nem Neustart des Adapter funktioniert er wieder.

Spotify 1.2.2
Admin 6.2.23
Node.js 14.19.1

**Comment by Apollon77** [comment]
503 heisst an sich das der Dienst gerade nicht verfügbar ist ... Und ja ohne ein Debug log was das zeigt kommen wir nicht weiter

**Comment by andre-bu** [comment]
@Apollon77 Hab jetzt den Adapter auf Debug Log umgestellt. Ergebnis kommt dann.

**Comment by Maschine20** [comment]
Hallo,

ich habe das gleiche verhalten und kann das reproduzieren.  Allerdinds ist es nicht immer so, dass der Haken bei "Verbunden mit Gerät oder Dienst" weg ist. . Adapterverision ist v1.2.2:


Log:
`

spotify-premium.0 | 2023-01-01 14:05:58.563 | debug | context type: ""
-- | -- | -- | --
spotify-premium.0 | 2023-01-01 14:05:58.562 | warn | unexpected api response http 503; continue polling
spotify-premium.0 | 2023-01-01 14:05:58.327 | debug | spotify api call... /v1/me/player;
spotify-premium.0 | 2023-01-01 14:05:58.327 | debug | call status polling
spotify-premium.0 | 2023-01-01 14:05:48.327 | debug | context type: ""
spotify-premium.0 | 2023-01-01 14:05:48.244 | debug | spotify api call... /v1/me/player;
spotify-premium.0 | 2023-01-01 14:05:48.244 | debug | call status polling
spotify-premium.0 | 2023-01-01 14:05:38.244 | debug | context type: ""
spotify-premium.0 | 2023-01-01 14:05:38.177 | debug | spotify api call... /v1/me/player;
spotify-premium.0 | 2023-01-01 14:05:38.177 | debug | call status polling
spotify-premium.0 | 2023-01-01 14:05:28.177 | debug | context type: ""
spotify-premium.0 | 2023-01-01 14:05:28.100 | debug | spotify api call... /v1/me/player;
spotify-premium.0 | 2023-01-01 14:05:28.100 | debug | call status polling
spotify-premium.0 | 2023-01-01 14:05:18.100 | debug | context type: ""
spotify-premium.0 | 2023-01-01 14:05:18.039 | debug | spotify api call... /v1/me/player;
spotify-premium.0 | 2023-01-01 14:05:18.039 | debug | call status polling
spotify-premium.0 | 2023-01-01 14:05:08.039 | debug | context type: ""
spotify-premium.0 | 2023-01-01 14:05:07.975 | debug | spotify api call... /v1/me/player;
spotify-premium.0 | 2023-01-01 14:05:07.975 | debug | call status polling
spotify-premium.0 | 2023-01-01 14:04:57.974 | debug | context type: ""
spotify-premium.0 | 2023-01-01 14:04:57.888 | debug | spotify api call... /v1/me/player;
spotify-premium.0 | 2023-01-01 14:04:57.887 | debug | call status polling
spotify-premium.0 | 2023-01-01 14:04:47.887 | debug | context type: ""
spotify-premium.0 | 2023-01-01 14:04:47.792 | debug | spotify api call... /v1/me/player;
spotify-premium.0 | 2023-01-01 14:04:47.792 | debug | call status polling
spotify-premium.0 | 2023-01-01 14:04:37.792 | debug | context type: ""
spotify-premium.0 | 2023-01-01 14:04:37.715 | debug | spotify api call... /v1/me/player;
spotify-premium.0 | 2023-01-01 14:04:37.715 | debug | call status polling
spotify-premium.0 | 2023-01-01 14:04:27.714 | debug | context type: ""
spotify-premium.0 | 2023-01-01 14:04:27.642 | debug | spotify api call... /v1/me/player;
spotify-premium.0 | 2023-01-01 14:04:27.641 | debug | call status polling
spotify-premium.0 | 2023-01-01 14:04:17.641 | debug | context type: ""
spotify-premium.0 | 2023-01-01 14:04:17.573 | debug | spotify api call... /v1/me/player;
spotify-premium.0 | 2023-01-01 14:04:17.573 | debug | call status polling
spotify-premium.0 | 2023-01-01 14:04:07.573 | debug | context type: ""
spotify-premium.0 | 2023-01-01 14:04:07.512 | debug | spotify api call... /v1/me/player;
spotify-premium.0 | 2023-01-01 14:04:07.512 | debug | call status polling
spotify-premium.0 | 2023-01-01 14:03:57.511 | debug | context type: ""
spotify-premium.0 | 2023-01-01 14:03:57.441 | debug | spotify api call... /v1/me/player;
spotify-premium.0 | 2023-01-01 14:03:57.441 | debug | call status polling
spotify-premium.0 | 2023-01-01 14:03:52.509 | debug | trigger: devices.availableDeviceListString -> {"val":"DESKTOP-EGV8K0V","ack":true}
spotify-premium.0 | 2023-01-01 14:03:52.508 | debug | trigger:  devices.deviceListIds ->  {"val":"073e1d20519b16b2ef186c5e6b6fee966c41525b;af7e8f21fd45cc035678e74c5539f116a0a1e9d9;3d2505363533b7c8081f845c273490754bfc6837;c7a6197538d44df88ec557b55946d73c027c0437;eacbbe474e6af5ba01c9223b29c97e71475b74a2;6c6069974e3f26a6d9f3573c95dffa0240a695a9;social-connect-f0968c6bc8104a2f4b2c74967cbace6a;410817eeefc7ff90f64e30f132bd5115159c4feb","ack":true}
spotify-premium.0 | 2023-01-01 14:03:52.447 | debug | spotify api call... /v1/me/player/devices;
spotify-premium.0 | 2023-01-01 14:03:52.447 | debug | call device polling
spotify-premium.0 | 2023-01-01 14:03:47.440 | debug | context type: ""
spotify-premium.0 | 2023-01-01 14:03:47.379 | debug | spotify api call... /v1/me/player;
spotify-premium.0 | 2023-01-01 14:03:47.378 | debug | call status polling

`

**Comment by manuxi** [comment]
+1
