### ISSUE TITLE
Problem with DP progress 

### ISSUE THREAD

**Issue by andre-bu** [iobroker-community-adapters/ioBroker.spotify-premium#167]
**Describe the bug**  
Hello, I have a problem with the data points:
spotify-premium.0.player.progress
spotify-premium.0.player.progressMs
spotify-premium.0.player.progressPercentage
They only show a value every 10 seconds. In the time in between there is zero in the DP.

**To Reproduce**  
1. Go to 'Play an Track'
2. 
3. 
4. See error in DP

**Expected behavior**  
Permanent display of the playing time

**Screenshots & Logfiles**  
A short Screenrecord to show the Problem.
https://youtu.be/5yiIYjP7KnY

**Versions:**  
 - Adapter version: 1.2.2
 - JS-Controller version: 4.0.23
 - Node version: 14.19.1
 - Operating system: Debian 11

**Comment by sbormann** [comment]
+1

**Comment by MK-66** [comment]
For your information: In version 1.2.1 the DP spotify-premium.0.player.progressPercentage still works normally. Only from V1.2.2 up to V1.3.1 the progressPercentage has this bug that it jumps back and forth between value and zero (null).

**Comment by n1tr0-5urf3r** [comment]
Duplicate #339 with a fix ready :)

**Comment by mcm1957** [comment]
fixed with 1.4.0
