### ISSUE TITLE
Any support or bug fixing?

### ISSUE THREAD

**Issue by Sascha8** [iobroker-community-adapters/ioBroker.spotify-premium#177]
no life signs since months here

**Comment by Trrw** [comment]
I would be very happy about an update. Unfortunately the adapter crashes and some more features could be added...

**Comment by mcm1957** [comment]
> I would be very happy about an update. Unfortunately the adapter crashes and some more features could be added...

If the adapter crashed there should be any logs. Please attach them.
I cannot ensure that someone will take care  but without info there would for sure be no action

**Comment by Trrw** [comment]
I have already given up. Unfortunately, I do not know adapter programming. The last update is so long ago. Many functions would be possible. Have unfortunately only problems with the adapter (songs are not played, albums can not be retrieved (album ID is not accepted), adapter crashed, and so on).
I have built a solution via detours via FHEM. There the Spotify module works without problems.
