### ISSUE TITLE
UseForPlayback - ERROR 404

### ISSUE THREAD

**Issue by djmarc75** [iobroker-community-adapters/ioBroker.spotify-premium#178]
Hi,
since a few days without using the Adapter i startet to create some new scripts with spotify usages.
So i tried to set the DP "useForPlayback" of some devices to TRUE and i got following results in LOGS (debug):

`<html><body>

spotify-premium.0 | 2023-02-23 14:43:46.701 | error | could not execute command: 404
-- | -- | -- | --
spotify-premium.0 | 2023-02-23 14:43:45.324 | debug | spotify api call... /v1/me/player; {"device_ids":["33a22bdc-bd90-4287-80cb-3a79ff786dff_amzn_1"],"play":true}
spotify-premium.0 | 2023-02-23 14:43:45.323 | debug | trigger:  /\.useForPlayback$/ ->  {"val":true,"ack":false,"ts":1677159825317,"q":0,"from":"system.adapter.admin.0","user":"system.user.admin","lc":1677159825317}

</body>
</html>`

Nothing happens so i can´t use this adapter for my usages anymore - since this bug (?) was fixed.

**Versions:**  
 - Adapter version: 1.2.2
 - JS-Controller version: 4.0.24
 - Node version: 16.19.1
 - Operating system: Debian Bullseye

Thanks for check and maybe fix

**Comment by Smibser** [comment]
I have the same behavior

**Comment by djmarc75** [comment]
fixed by Spotify !
