### ISSUE TITLE
Adapter not starting with Admin 6.5.7

### ISSUE THREAD

**Issue by PatrickZ1990** [iobroker-community-adapters/ioBroker.spotify-premium#197]
Since the update to Admin 6.5.7, the Spotify adapter is immediately terminated. The log shows the following:

host.HomeAutomationRaspi | 2023-06-10 12:32:08.642 | warn | Do not restart adapter system.adapter.spotify-premium.0 because restart loop detected
host.HomeAutomationRaspi | 2023-06-10 12:32:08.642 | info | Restart adapter system.adapter.spotify-premium.0 
host.HomeAutomationRaspi | 2023-06-10 12:32:08.641 | error | instance system.adapter.spotify-premium.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
host.HomeAutomationRaspi | 2023-06-10 12:32:08.641 | error | Caught by controller[1]: no ids in trackListIds
host.HomeAutomationRaspi | 2023-06-10 12:32:08.640 | error | Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). 

It seems to be some bug with the "trackListIds", but that error does not show up everytime. The host blocked restarting the adapter due to this issues.

**Comment by aruttkamp** [comment]
@PatrickZ1990  - Ich habe mir den Adapter installiert und eingerichtet und ich kann aktuell nicht feststellen , dass das von dir beschriebene Verhalten auftritt. Admin Version 6.8.0
Kannst Du mich bitte mit der Info versorgen ob es bei dir immer noch so ist dass der Adapter nicht geht ? 
Ausserdem wäre es hilfreich zu wissen wieviele Tracklists du eingerichtet hast ? Wenn ich das im Code richtig lese könnte es auch damit zu tun haben das ich es nicht reproduzieren kann.

**Comment by aruttkamp** [comment]
2 weeks no reaction - close
