### ISSUE TITLE
DP progress stutters

### ISSUE THREAD

**Issue by sbormann** [iobroker-community-adapters/ioBroker.spotify-premium#199]
see #167 

DP progress stutters and shows altenating zero and the acutal value.

**Comment by MK-66** [comment]
For your information: In version 1.2.1 the DP spotify-premium.0.player.progressPercentage still works normally. Only from V1.2.2 up to V1.3.1 the progressPercentage has this bug that it jumps back and forth between value and zero (null).

**Comment by Exorzist6666** [comment]
Same issue for me

**Comment by n1tr0-5urf3r** [comment]
Duplicate #339  with a fix ready :)
