### ISSUE TITLE
Please fix issues reported by adapter checker

### ISSUE THREAD

**Issue by mcm1957** [iobroker-community-adapters/ioBroker.spotify-premium#204]
Please fix issues reported by adapter checker

❗ [E605] No actual year found in copyright. Please add "Copyright (c) 2019-2023 twonky4 [twonky4@gmx.de](mailto:twonky4@gmx.de)" at the end of [README.md](https://github.com/iobroker-community-adapters/ioBroker.spotify-premium/blob/master/README.md)
 ❗ [E802] No topics found in the repository. Please go to "https://github.com/iobroker-community-adapters/ioBroker.spotify-premium", press the settings button beside the about title and add some topics.
 ❗ [E701] No actual year found in LICENSE. Please add "Copyright (c) 2019-2023 twonky4 [twonky4@gmx.de](mailto:twonky4@gmx.de)" at the start of LICENSE

**Comment by aruttkamp** [comment]
[E605] + [E701] corrected.
[E802] must be corrected with write access to repository.
Pull request follows ....

**Comment by mcm1957** [comment]
[E802] fixed
