### ISSUE TITLE
Error 400 with playUri

### ISSUE THREAD

**Issue by khnz** [iobroker-community-adapters/ioBroker.spotify-premium#259]
'playUri' doesn't work for me, it always returns Error 400. I suspect that a 'JSON.stringify()' is missing in main.js line 1827.

1. my javascript snippet
```
setState('spotify-premium.1.player.playUri', {
  "device_id": "...",
  "context_uri": "spotify:user:...:playlist:...",
  "offset": {
    "position": 0
  },
  "position_ms":0
});
```
2. in the log file
`error: spotify-premium.1 (...) could not execute command: 400`

**Comment by mcm1957** [comment]
please add version info
adapter
js-controller
node
O/S

**Comment by khnz** [comment]
adapter: v1.2.2
js-controller: 5.0.13
node: v18.18.2
O/S: Debian 12.2

**Comment by aruttkamp** [comment]
fixed 2 weeks ago and no one reports error .... closed
