### ISSUE TITLE
Tracklist HTML table - Current played track is not highlighted

### ISSUE THREAD

**Issue by MK-66** [iobroker-community-adapters/ioBroker.spotify-premium#283]
**Describe the bug**  
Since adapter version V1.2.2 the active (current) track in the tracklist HTML table (spotify-premium.0.html.tracks) is no longer highlighted in green and marked with the active playing icon. 

Only the first track in the list is always marked as active, regardless of which track from the list is currently playing. Setting the track via click still works normally, the track is just not marked as active.

This bug has been present since versions 1.2.2 up to V1.3.1, in V1.2.1 this still works correctly.

**Expected behavior**  
Active track should be marked correctly in the tracklist HTML table (spotify-premium.0.html.tracks) as it was in V1.2.1

**Versions:**  
 - Adapter version: 1.3.1
 - JS-Controller version: 5.0.16
 - Node version: 18.18.2
 - Operating system: Debian 12

**Comment by EngelenJ** [comment]
Same issue here.

**Comment by Exorzist6666** [comment]
Same for me. 
Only first is highlighted not the played one

**Comment by aruttkamp** [comment]
I will try to fix it until christmas.

**Comment by EngelenJ** [comment]
Good evening. I would like to ask if there is a fix in sight? Thanks for helping with this.

**Comment by EngelenJ** [comment]
I'm sorry to ask, but is it possible to solve this issue?

**Comment by mcm1957** [comment]
@aruttkamp 
Any news? Could you please give some feedback (even if it is something like no time to work on this)

**Comment by MK-66** [comment]
The problem regarding the tracklist html table described above still exists with V1.4.0.

**Comment by EngelenJ** [comment]
> fixed 1.5.0

Nice! Works great!
