### ISSUE TITLE
Progress of media not updated correctly

### ISSUE THREAD

**Issue by n1tr0-5urf3r** [iobroker-community-adapters/ioBroker.spotify-premium#339]
**Describe the bug**  
The progress of playing media is not updated correctly. The progress always falls back to its default value (0) and only updates once after an API update. This is likely because the internal timer function to calculate returns undefined.

**To Reproduce**  
1. Play media via spotify.
2. Check the value of `progress` and `progressMs` in the object tree.

**Expected behavior**  
The value should be updated approx. every second. However, the value is only updated once in the status update interval. Between every polling update, the value is undefined thus displaying 00:00 in embedded widgets.

**Versions:**  
 - Adapter version: 1.3.1
 - JS-Controller version: 5.0.19
 - Node version: v18.20.0
 - Operating system: Debian GNU/Linux 12

**Additional context**  
I got a fix ready in my fork, PR coming soon.

**Comment by mcm1957** [comment]
duplicate #167
