### ISSUE TITLE
Adapter causing a lot of DNS traffic

### ISSUE THREAD

**Issue by n1tr0-5urf3r** [iobroker-community-adapters/ioBroker.spotify-premium#341]
**Describe the bug**  
The adapter causes a lot of DNS queries to api.spotify.com. After a while, this results in my DNS server rate limitting the iobroker host. The iobroker host then sends out a whole lot more DNS queries because it cannot resolve it anymore.

**To Reproduce**  
1. Have the adapter running and listen to some music.

**Expected behavior**  
The DNS result should be cached in some way.

**Screenshots & Logfiles**  
Plot of DNS queries per host in my network. Starting at ~11:00, the dark blue / grey part is the iobroker host querying for api.spotify.com

![grafik](https://github.com/iobroker-community-adapters/ioBroker.spotify-premium/assets/10401990/88d23450-a61b-488c-8507-31886fcd40c5)

**Versions:**  
    Adapter version: 1.3.1
    JS-Controller version: 5.0.19
    Node version: v18.20.0
    Operating system: Debian GNU/Linux 12

**Comment by n1tr0-5urf3r** [comment]
I got a potential fix for this using the [dns-lookup-cache](https://www.npmjs.com/package/dns-lookup-cache) library in my dns-cache branch: https://github.com/n1tr0-5urf3r/ioBroker.spotify-premium/commit/9061e751bb15fd3ed71c649a0fae4dcabf58352e

**Comment by mcm1957** [comment]
added at 1.5.0
