### ISSUE TITLE
script Tracklist funktioniert nicht

### ISSUE THREAD

**Issue by dos1973** [iobroker-community-adapters/ioBroker.spotify-premium#52]
Hi,

das Track Script funktioniert nicht.
Die Pfade zum neuen Adapter habe ich angepasst
alt: spotify-premium.0.playbackInfo.playlist.trackList
neu: spotify-premium.0.player.playlist.trackList

aber ich erhalten "undefined" Fehler in der Ausgabe und kann den Fehler nicht finden.

Danke für deine Hilfe

**Comment by twonky4** [comment]
Welche Version benutzt du?

**Comment by dos1973** [comment]
Hi,

ich nutze die Version 1.0.0
aber nach suchen und mehr verstehen muss ich mein Issue etwas relativieren.
Die Trackliste aus dem Adapter funktioniert - Sorry für die Verwirrung.

Diese Darstellung kann ich leider nicht modifizieren, nach meinen Wünschen (weiß nicht wie es geht) also habe ich dieses Script versucht.
https://github.com/twonky4/ioBroker.spotify-premium/wiki/Html-Tracklist

Hier habe ich die Pfade auf die neuen DP angepasst, aber es klappt leider immer noch nicht.

ich suche eine Darstellung der Tracks, wie diese im Forum immer gezeigt werden... 
einfach, etwas Abstand zwischen den Titeln und das Album  /Interpret etwas kleiner darunter. Das Forum habe ich gefühlt mehrfach durch, aber die erfolgte Forumsmigration macht es nicht einfacher.

Für deine Unterstützung/ Hilfestellung, vielen Dank im Vorraus.

**Comment by senger1985** [comment]
Bei mir tauchen auch keine Informationen, unter Playlist auf.
trackList, trackListArray, etc. sind leer.
Adapter 1.0.0
