### ISSUE TITLE
Device wechseln funktioniert mit Blockly nicht

### ISSUE THREAD

**Issue by valentin38315** [iobroker-community-adapters/ioBroker.spotify-premium#58]
Hi,

Wenn ich manuell in die Objekte reingehe und den Button zum switchen der einzelnen Geräte klicke wechselt das Lied auf das andere Gerät. Wenn ich das ganze zeitgesteuert über ein Blockly script machn will spielt er zwar das Lied, aber man hört es nicht weil er irgendwie den Teil "steuere ObjektID (Playback this device...) mit wahr" nicht richtig annimmt. Ich dachte dass es am Button liegt und habe das Objekt zu einem Switch umgeändert. Der ändert sich dann beim drücken auf true and sofort wieder auf false.

Hat wer eine Lösung? :)

**Comment by wilddeuces** [comment]
Bei mir funktioniert das Device wechseln auch nicht, auch schon in Objekte nicht.

**Comment by michipi85** [comment]
Funtkioniert definitv seit mindestens v1.0.0 bei mir. Welche Version habt ihr im Einsatz?
