### ISSUE TITLE
Playlisten von Fremd Accounts sind nicht sichtbar

### ISSUE THREAD

**Issue by JBSullivan** [iobroker-community-adapters/ioBroker.spotify-premium#67]
Unter der Playlist Anzeige  ( {spotify-premium.0.html.playlists} ) werden nur Playlisten aufgeführt, die von dem eigenen Account, aus einem Familien Account oder von Spotfiy selber stammen.

Playlisten von Nutzern denen ich Folge und deren Playliste (mit einer Apple APP erzeugt) in meiner Spotfiy Biliothek vorhanden sind, werden nicht von dem Adapter übernommen. Der Besitzer hat seine Playlist auch öffentlich gemacht.

Wie gesagt, in meiner Spotify Biliothek taucht diese "fremde" Playlist auf, wird aber vom Adapter nicht übernommen.

**Comment by heymkeyu** [comment]
Sind das Playlisten, die nicht nur geteilt sind, sondern auch noch "gemeinsam"? 
Die kriege ich ebenfalls nicht.
Playlisten von Nutzern, denen ich folge und die ich einmal über die Spotify App  oder DesktopApp abgespielt habe, tauchen in der Liste auf und können verwendet werden.

**Comment by Xyolyp** [comment]
Meine eigenen als "Gemeinsame Playlist" markierten Playlists erhalte ich leider auch nicht in 1.1.3
![image](https://user-images.githubusercontent.com/13995942/128695077-96c79edf-d1a0-4831-b2da-01daa6e94025.png)
