### ISSUE TITLE
remove track from playlist

### ISSUE THREAD

**Issue by moschnetwork** [iobroker-community-adapters/ioBroker.spotify-premium#75]
thank you for this great adapter ;)

I cant find a solution how to remove a track from playlist.

i found this link from spotify api:
https://developer.spotify.com/documentation/web-api/reference/playlists/remove-tracks-playlist/

I hope someone has found a solution

thank you

**Comment by twonky4** [comment]
It's currently not possible with the adapter because the permission for "edit playlist" endpoint are not requested during authorization.

**Comment by rehmosch** [comment]
> 
> 
> It's currently not possible with the adapter because the permission for "edit playlist" endpoint are not requested during authorization.
hey twonky4,

thank you for your fast responding ;) 

Apparently it is possible to delete a song from the playlist via http comand. Here it would be with the "Spotify Premium Adapter" to read the playlist & song ID URIs from the adapter and send an http request comand with 2 variables to delete a song from the playlist, wouldn't it?

Is it worth investing time here?
https://developer.spotify.com/documentation/web-api/reference/playlists/remove-tracks-playlist/
https://developer.spotify.com/community/news/2018/06/12/changes-to-playlist-uris/

**Comment by rehmosch** [comment]
i try this link:
https://developer.spotify.com/console/delete-playlist-tracks/?playlist_id=4gNMtOsPquZXWCeviC4mVG&body=%7B%22tracks%22%3A%5B%7B%22uri%22%3A%22spotify%3Atrack%3A2DB2zVP1LVu6jjyrvqD44z%22%2C%22positions%22%3A%5B0%5D%7D%2C%7B%22uri%22%3A%22spotify%3Atrack%3A5ejwTEOCsaDEjvhZTcU6lg%22%2C%22positions%22%3A%5B1%5D%7D%5D%7D

But I Got error 400

**Comment by twonky4** [comment]
It is not just call an url. At first you have to add `playlist-modify-private` and/or `playlist-modify-public` to the code line:
https://github.com/twonky4/ioBroker.spotify-premium/blob/4f992c01ecf6998948079f6d4bdab68052974ddc/main.js#L1694

At second you have to re-authorize the adapter.

And the you can call something like: https://github.com/twonky4/ioBroker.spotify-premium/blob/4f992c01ecf6998948079f6d4bdab68052974ddc/main.js#L1790-L1794
but all in the scope of the adapter.

**Comment by rehmosch** [comment]
hey twonky,

ich bin eine nooobin ;) wenn ich diesen o.g Code in deinen Script einfüge dann funktioniert es? Sorry, für diese blöde Frage und trotz allem ein HERZLICHES DANKESCHÖN ;)

Mein Problem ist:
Dass ich keinen Thumb up Button / Herzchen Button benötige, sondern der dislike bzw. der Thumb down Button viel wichtiger für mich/uns ist. 

Leider gibt es diese negativen Bewertungen  nur bei Google Music oder bei Pandora Radio und ich bin wirklich am verzweifeln, da ich keinen Mainstream höre und keine Herzchen benötige.

Vielen lieben Dank für deine Bemühnungen.
