### ISSUE TITLE
Lautstärke-Wert nicht per Script änderbar

### ISSUE THREAD

**Issue by maddingamer** [iobroker-community-adapters/ioBroker.spotify-premium#77]
Moin Moin, 
Ich würde gerne per Script die Lautstärke eines Geräts ändern. Per Slider im VIS funktioniert es tadellos, per Script leider nicht. Das gleiche Script funktioniert jedoch bei einem eigenen Datenpunkt ohne Probleme.. Gibt es da eine möglichkeit das zu lösen?

`    setState('spotify-premium.0.devices.DEVICEID.volume', 10);
`

Und wo ich schonmal hier bin: 
Gibt es eine einfachere Methode, um ein zufälliges Album eines Interpreten zu spielen (Stichwort Hörspiel) als alle URIs der Alben jeweils in eine Variable zu schreiben und dann per Zufall eine Variable zu wählen?

**Comment by twonky4** [comment]
Und wenn du ```setState('spotify-premium.0.player.device.volume', 10);``` machst? Das `player` Objekt stellt immer die aktuelle Wiedergabe dar und soweit ich weiß kannst du immer nur vom aktuellem Device die Lautstärke ändern.

Bei der 2. Sache frag doch mal im Forum nach.

**Comment by maddingamer** [comment]
Mit dem player objekt funktioniert es besser, danke für den Tipp :) 

Zu 2.: Mit playURI aus 1.1.0 hat es ein paar Tage lang funktioniert, aber irgendwie ist schon wieder der Wurm drin.. werde also wohl abwarten müssen bis der Adapter aktualisiert wird..
