### ISSUE TITLE
Gezielt ein Album abspielen

### ISSUE THREAD

**Issue by Trrw** [iobroker-community-adapters/ioBroker.spotify-premium#79]
Leider lassen sich gezielt keine Alben abspielen ("spotify:album:XXXXX"). Mit der Trackid (spotify-premium -> player -> trackid) lassen sich nur einzelne Songs aufrufen. Eine Albumid gibt es leider nicht.

**Comment by Trrw** [comment]
Ich habe gesehen, das dies nun bei Version 1.1.0 funktionieren soll. Wenn ich unter playUri -> {"device_id“:“DEVICEID,“context_uri":"spotify:album:0lc1TxAzpSHI7DGhgdWuMI"} eingebe, wird dies rot quittiert und nicht abgespielt.

**Comment by Newan** [comment]
selbe Problem funktioniert bei mir auch nicht. Dabei wäre dies eine Super Funktion!

**Comment by Newan** [comment]
Nachtrag: Funktioniert. Ist ein Dokufehler etc.

1. Objekt von Objekt auf string stellen
2. in der Main.js ändern auf: ` sendRequest('/v1/me/player/play?' + querystring.stringify(query), 'PUT', send, true).catch(function(err) {`

Alternativ kein String sondern Objekt übergeben. Problem ist bei mir das ich per Javascript dann den Fehler:

setForeignState: undefined is not a valid state value

bekomme. Somit blieb für mich nur Variante 1
