### ISSUE TITLE
Doppelte Geräte

### ISSUE THREAD

**Issue by Ghost-Talker** [iobroker-community-adapters/ioBroker.spotify-premium#80]
Ein Amazon Echo taucht in den devices immer öfter auf, wobei nur der letzte wirklich funktioniert.

![image](https://user-images.githubusercontent.com/38839903/79079392-0c25b280-7d0f-11ea-9d9f-0dae9b11625a.png)

amazon echo listet multiple times in devices folder

**Comment by GermanBluefox** [comment]
![image](https://user-images.githubusercontent.com/4582016/142251403-6be10fb3-2ce4-4458-9719-52c146d3487d.png)
