### ISSUE TITLE
Mehrere Probleme

### ISSUE THREAD

**Issue by wizzardking** [iobroker-community-adapters/ioBroker.spotify-premium#83]
Vielen Dank für den Spotify Adapter.

Leider funktioniert dieser bei mir in der Version 1.1 nicht richtig.
Ich kann zwar im VIS alles korrekt anzeigen was aktuell gerade gespielt wird, wenn ich aber versuche den Track zu überspringen oder das Gerät zu ändern, kommt meist nur eine Fehlermeldung in den Logs:

spotify-premium.0 | 2020-05-31 12:17:39.276 | error | (26721) could not execute command: 403
-- | -- | -- | --
spotify-premium.0 | 2020-05-31 12:17:39.276 | warn | (26721) Error at /opt/iobroker/node_modules/iobroker.spotify-premium/main.js:318:38 at tryCallOne (/opt/iobroker/node_modules/promise/lib/core.js:37:12) at /opt/iobroker/node_modules/promi
spotify-premium.0 | 2020-05-31 12:17:39.276 | warn | (26721) Error at sendRequest (/opt/iobroker/node_modules/iobroker.spotify-premium/main.js:206:21) at Object.listenOnSkipPlus [as func] (/opt/iobroker/node_modules/iobroker.spotify-premium/main
spotify-premium.0 | 2020-05-31 12:17:39.276 | warn | (26721) http request error not handled, please debug
spotify-premium.0 | 2020-05-31 12:11:27.293 | error | (26721) could not execute command: 403
spotify-premium.0 | 2020-05-31 12:11:27.293 | warn | at process._tickCallback (internal/process/next_tick.js:61:11)
spotify-premium.0 | 2020-05-31 12:11:27.293 | warn | at flush (/opt/iobroker/node_modules/asap/raw.js:50:29)
spotify-premium.0 | 2020-05-31 12:11:27.293 | warn | at /opt/iobroker/node_modules/promise/lib/core.js:123:15
spotify-premium.0 | 2020-05-31 12:11:27.293 | warn | at tryCallOne (/opt/iobroker/node_modules/promise/lib/core.js:37:12)
spotify-premium.0 | 2020-05-31 12:11:27.293 | warn | at /opt/iobroker/node_modules/iobroker.spotify-premium/main.js:318:38
spotify-premium.0 | 2020-05-31 12:11:27.293 | warn | (26721) Error
spotify-premium.0 | 2020-05-31 12:11:27.293 | warn | at tryOnImmediate (timers.js:676:5)
spotify-premium.0 | 2020-05-31 12:11:27.293 | warn | at runCallback (timers.js:705:18)
spotify-premium.0 | 2020-05-31 12:11:27.293 | warn | at Immediate.setImmediate [as _onImmediate] (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5384:37)
spotify-premium.0 | 2020-05-31 12:11:27.293 | warn | at Object.stateChange (/opt/iobroker/node_modules/iobroker.spotify-premium/main.js:52:10)
spotify-premium.0 | 2020-05-31 12:11:27.293 | warn | at Object.setExternal (/opt/iobroker/node_modules/iobroker.spotify-premium/lib/cache.js:256:2)
spotify-premium.0 | 2020-05-31 12:11:27.293 | warn | at trigger (/opt/iobroker/node_modules/iobroker.spotify-premium/lib/cache.js:217:11)
spotify-premium.0 | 2020-05-31 12:11:27.293 | warn | at Array.forEach (<anonymous>)
spotify-premium.0 | 2020-05-31 12:11:27.293 | warn | at /opt/iobroker/node_modules/iobroker.spotify-premium/lib/cache.js:223:19
spotify-premium.0 | 2020-05-31 12:11:27.293 | warn | at Object.listenOnSkipPlus [as func] (/opt/iobroker/node_modules/iobroker.spotify-premium/main.js:1814:5)
spotify-premium.0 | 2020-05-31 12:11:27.293 | warn | at sendRequest (/opt/iobroker/node_modules/iobroker.spotify-premium/main.js:206:21)
spotify-premium.0 | 2020-05-31 12:11:27.293 | warn | (26721) Error
spotify-premium.0 | 2020-05-31 12:11:27.292 | warn | (26721) http request error not handled, please debug

**Comment by GermanBluefox** [comment]
403 => not authenticated.
