### ISSUE TITLE
No Contenttype, Duration and Metadata for Podcasts

### ISSUE THREAD

**Issue by narolinus** [iobroker-community-adapters/ioBroker.spotify-premium#84]
When playing Podcasts in Spotify the Adapter does not load any additional Information. The contenttype, duration, albumimage, artist etc. are all empty.

The log does not seem to show any significant information on that issue:
`

spotify-premium.0 | 2020-06-19 15:02:16.011 | debug | (2367) save state: player.progress -> "104:08"
-- | -- | -- | --
spotify-premium.0 | 2020-06-19 15:02:16.011 | debug | (2367) save state: player.progressPercentage -> 0
spotify-premium.0 | 2020-06-19 15:02:16.011 | debug | (2367) save state: player.progressMs -> 6248926
spotify-premium.0 | 2020-06-19 15:02:16.010 | debug | (2367) save state: player.isPlaying -> false
spotify-premium.0 | 2020-06-19 15:02:15.901 | debug | (2367) spotify api call.../v1/me/player;
spotify-premium.0 | 2020-06-19 15:02:15.900 | debug | (2367) call status polling
spotify-premium.0 | 2020-06-19 15:02:14.951 | debug | (2367)  spotify api  call.../v1/users/perryrhodan./playlists/1mZWPNdwVjJwH88MaIk1mS/tracks?fields=total%2Coffset%2Citems(added_at%2Cadded_by.id%2Ctrack(name%2Cid%2Cartists(name%2Cid)%2Cduration_ms%2Calb
spotify-premium.0 | 2020-06-19 15:02:14.897 | silly | (2367)  States user redis pmessage  spotify-premium.0.*/spotify-premium.0.player.progressPercentage:{"val":null,"ack":true,"ts":1592571734884,"q":0,"from":"system.adapter.spotify-premium.0","user":"syst
spotify-premium.0 | 2020-06-19 15:02:14.887 | silly | (2367)  States user redis pmessage  spotify-premium.0.*/spotify-premium.0.player.progressMs:{"val":6249674,"ack":true,"ts":1592571734884,"q":0,"from":"system.adapter.spotify-premium.0","user":"system.us
spotify-premium.0 | 2020-06-19 15:02:14.886 | silly | (2367)  States user redis pmessage  spotify-premium.0.*/spotify-premium.0.player.progress:{"val":"104:09","ack":true,"ts":1592571734884,"q":0,"from":"system.adapter.spotify-premium.0","user":"system.use
spotify-premium.0 | 2020-06-19 15:02:14.882 | debug | (2367) save state: player.progressPercentage -> null
spotify-premium.0 | 2020-06-19 15:02:14.882 | debug | (2367) save state: player.progressMs -> 6249674
spotify-premium.0 | 2020-06-19 15:02:14.881 | debug | (2367) save state: player.progress -> "104:09"
spotify-premium.0 | 2020-06-19 15:02:13.880 | debug | (2367) context type:

`

I am new to iobroker, so I haven't really gotten to the bottom of it yet. But my first impression is is that this type has not yet been implemented. Is it possible to add it with a later version?

**Comment by greeenit** [comment]
I got the Same Problem. While researching I found this New API Endpoints That were released in March. Would be Great of you could implement them. 

https://developer.spotify.com/community/news/2020/03/20/introducing-podcasts-api/
