### ISSUE TITLE
Shuffle aktiviert sich automatisch

### ISSUE THREAD

**Issue by mvenus2** [iobroker-community-adapters/ioBroker.spotify-premium#87]
Shuffle aktiviert sich immer wieder automatisch, wenn ich eine Playlist abspiele. 

1. Ich spiele eine Playlist -> Shuffle ist aktiviert
2. Ich deaktiviere Shuffle
3. Ich Spiele eine andere Playlist -> Shuffle ist automatisch wieder aktiviert

**Comment by canim60** [comment]
Den Adapter kannst du du in die Tonne hauen!, Ist ja schön das der Entwickler sich die Zeit nimmt und sowas macht,letztes Update vor2 Jahren. Ein Adapter macht dann Sinn wenn es regelmäßig bug fixes duchgeführt wird. Der Entwickler soll das ganze einstellen und löschen! oder weiter entwickeln...

**Comment by bellerG** [comment]
> Shuffle aktiviert sich immer wieder automatisch, wenn ich eine Playlist abspiele.
> 
> 1. Ich spiele eine Playlist -> Shuffle ist aktiviert
> 2. Ich deaktiviere Shuffle
> 3. Ich Spiele eine andere Playlist -> Shuffle ist automatisch wieder aktiviert

In den Adaptersettings gibt es dafür eine Einstellung, prüfen diese mal.

**Comment by GermanBluefox** [comment]
In 1.1.5 gibt es die Möglichkeit:
![image](https://user-images.githubusercontent.com/4582016/142250572-01a77478-f58a-4aaa-8aa8-366958ace139.png)
