### ISSUE TITLE
 error | (20489) erron in request: 403

### ISSUE THREAD

**Issue by moschnetwork** [iobroker-community-adapters/ioBroker.spotify-premium#88]
Servus, seit heute erhalte ich diesen Code. Ich kann nichts mehr kontrollieren (play, pause ...) sehe aber in der VIS Zeit, Track und Album.

Hat jemand eine Idee?

Ach ja, herzlichen Dank für diesen tollen Adapter ;)

`

potify-premium.0 | 2021-01-29 16:57:41.513 | error | (20489) erron in request: 403
-- | -- | -- | --
spotify-premium.0 | 2021-01-29 16:57:41.512 | warn | (20489) Error at /opt/iobroker/node_modules/iobroker.spotify-premium/main.js:262:38 at tryCallOne (/opt/iobroker/node_modules/promise/lib/core.js:37:12) at /opt/iobroker/node_modules/promi
spotify-premium.0 | 2021-01-29 16:57:41.511 | warn | (20489) Error at sendRequest (/opt/iobroker/node_modules/iobroker.spotify-premium/main.js:154:21) at listenOnShuffle (/opt/iobroker/node_modules/iobroker.spotify-premium/main.js:1820:12) a
spotify-premium.0 | 2021-01-29 16:57:41.511 | warn | (20489) http request error not handled, please debug
spotify-premium.0 | 2021-01-29 16:57:41.353 | error | (20489) erron in request: 403
spotify-premium.0 | 2021-01-29 16:57:41.353 | warn | (20489) Error at /opt/iobroker/node_modules/iobroker.spotify-premium/main.js:262:38 at tryCallOne (/opt/iobroker/node_modules/promise/lib/core.js:37:12) at /opt/iobroker/node_modules/promi
spotify-premium.0 | 2021-01-29 16:57:41.352 | warn | (20489) Error at sendRequest (/opt/iobroker/node_modules/iobroker.spotify-premium/main.js:154:21) at /opt/iobroker/node_modules/iobroker.spotify-premium/main.js:1571:16 at tryCallOne (/opt
spotify-premium.0 | 2021-01-29 16:57:41.351 | warn | (20489) http request error not handled, please debug
spotify-premium.0 | 2021-01-29 16:57:40.511 | error | (20489) erron in request: 403
spotify-premium.0 | 2021-01-29 16:57:40.510 | warn | (20489) Error at /opt/iobroker/node_modules/iobroker.spotify-premium/main.js:262:38 at tryCallOne (/opt/iobroker/node_modules/promise/lib/core.js:37:12) at /opt/iobroker/node_modules/promi
spotify-premium.0 | 2021-01-29 16:57:40.509 | warn | (20489) Error at sendRequest (/opt/iobroker/node_modules/iobroker.spotify-premium/main.js:154:21) at listenOnShuffle (/opt/iobroker/node_modules/iobroker.spotify-premium/main.js:1820:12) a
spotify-premium.0 | 2021-01-29 16:57:40.509 | warn | (20489) http request error not handled, please debug
spotify-premium.0 | 2021-01-29 16:57:40.360 | error | (20489) erron in request: 403
spotify-premium.0 | 2021-01-29 16:57:40.359 | warn | (20489) Error at /opt/iobroker/node_modules/iobroker.spotify-premium/main.js:262:38 at tryCallOne (/opt/iobroker/node_modules/promise/lib/core.js:37:12) at /opt/iobroker/node_modules/promi
spotify-premium.0 | 2021-01-29 16:57:40.359 | warn | (20489) Error at sendRequest (/opt/iobroker/node_modules/iobroker.spotify-premium/main.js:154:21) at /opt/iobroker/node_modules/iobroker.spotify-premium/main.js:1571:16 at tryCallOne (/opt
spotify-premium.0 | 2021-01-29 16:57:40.358 | warn | (20489) http request error not handled, please debug
spotify-premium.0 | 2021-01-29 16:57:31.994 | error | (20489) erron in request: 404
spotify-premium.0 | 2021-01-29 16:56:53.834 | info | (20489) starting. Version 1.0.0 in /opt/iobroker/node_modules/iobroker.spotify-premium, node: v12.20.1, js-controller: 3.2.12
spotify-premium.0 | 2021-01-29 16:56:47.434 | info | (28691) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
spotify-premium.0 | 2021-01-29 16:56:47.433 | info | (28691) terminating
spotify-premium.0 | 2021-01-29 16:56:47.400 | info | (28691) Got terminate signal TERMINATE_YOURSELF
spotify-premium.0 | 2021-01-29 16:53:02.396 | error | (28691) erron in request: 403

`

**Comment by bellerG** [comment]
I have exactly the same problem, no playlists can be changed either.
The status information about the player comes in correctly, however.

**Comment by px51** [comment]
Same here. Worked fine until yesterday. Turns out that the Spotify API is having some trouble understanding which devices are active and which are not. I get this error once Spotify has nothing active in der player anymore. Easy workaround ist, when you open the Spotify App and press the PlayButton. Maybe there is a way to integrate the suggtested fix somehow: 

https://github.com/spotify/web-api/issues/1325#issuecomment-639071348
