### ISSUE TITLE
missing objects in actual version

### ISSUE THREAD

**Issue by jolu1705** [iobroker-community-adapters/ioBroker.spotify-premium#92]
Actual iobroker stable is displaying errors in log

```
spotify-premium.0	2021-03-23 11:22:18.461	warn	(5682) State "spotify-premium.0.devices.860c3e969f5d1a40308ef730a58bf33306eadef5.isAvailable" has no existing object, this might lead to an error in future versions
--
  | spotify-premium.0	2021-03-23 11:22:18.453	warn	(5682) State "spotify-premium.0.devices.860c3e969f5d1a40308ef730a58bf33306eadef5.volume" has no existing object, this might lead to an error in future versions
  | spotify-premium.0	2021-03-23 11:22:18.452	warn	(5682) State "spotify-premium.0.devices.860c3e969f5d1a40308ef730a58bf33306eadef5.type" has no existing object, this might lead to an error in future versions
  | spotify-premium.0	2021-03-23 11:22:18.449	warn	(5682) State "spotify-premium.0.devices.860c3e969f5d1a40308ef730a58bf33306eadef5.name" has no existing object, this might lead to an error in future versions
  | spotify-premium.0	2021-03-23 11:22:18.448	warn	(5682) State "spotify-premium.0.devices.860c3e969f5d1a40308ef730a58bf33306eadef5.isRestricted" has no existing object, this might lead to an error in future versions
  | spotify-premium.0	2021-03-23 11:22:18.447	warn	(5682) State "spotify-premium.0.devices.860c3e969f5d1a40308ef730a58bf33306eadef5.isActive" has no existing object, this might lead to an error in future versions
  | spotify-premium.0	2021-03-23 11:22:18.445	warn	(5682) State "spotify-premium.0.devices.860c3e969f5d1a40308ef730a58bf33306eadef5.id" has no existing object, this might lead to an error in future versions
  | spotify-premium.0	2021-03-23 11:22:18.430	warn	(5682) State "spotify-premium.0.devices.860c3e969f5d1a40308ef730a58bf33306eadef5.useForPlayback" has no existing object, this might lead to an error in future versions
```

**Comment by Azathoth88** [comment]
Mein Log wird damit ebenfalls regelmäßig zugeballert:
`
<html>
<body>


spotify-premium.0 | 2021-06-27 07:08:51.666 | warn | State "spotify-premium.0.devices.6b11c5e40b14cf7a99563d65862f5fdb14bfdac4.isAvailable" has no existing object, this might lead to an error in future versions
-- | -- | -- | --
spotify-premium.0 | 2021-06-27 07:08:51.666 | warn | State "spotify-premium.0.devices.6b11c5e40b14cf7a99563d65862f5fdb14bfdac4.volume" has no existing object, this might lead to an error in future versions
spotify-premium.0 | 2021-06-27 07:08:51.665 | warn | State "spotify-premium.0.devices.6b11c5e40b14cf7a99563d65862f5fdb14bfdac4.type" has no existing object, this might lead to an error in future versions
spotify-premium.0 | 2021-06-27 07:08:51.665 | warn | State "spotify-premium.0.devices.6b11c5e40b14cf7a99563d65862f5fdb14bfdac4.name" has no existing object, this might lead to an error in future versions
spotify-premium.0 | 2021-06-27 07:08:51.665 | warn | State "spotify-premium.0.devices.6b11c5e40b14cf7a99563d65862f5fdb14bfdac4.isRestricted" has no existing object, this might lead to an error in future versions
spotify-premium.0 | 2021-06-27 07:08:51.664 | warn | State "spotify-premium.0.devices.6b11c5e40b14cf7a99563d65862f5fdb14bfdac4.isActive" has no existing object, this might lead to an error in future versions
spotify-premium.0 | 2021-06-27 07:08:51.661 | warn | State "spotify-premium.0.devices.6b11c5e40b14cf7a99563d65862f5fdb14bfdac4.id" has no existing object, this might lead to an error in future versions
spotify-premium.0 | 2021-06-27 07:08:51.661 | warn | State "spotify-premium.0.devices.6b11c5e40b14cf7a99563d65862f5fdb14bfdac4.useForPlayback" has no existing object, this might lead to an error in future versions
spotify-premium.0 | 2021-06-27 07:08:51.661 | warn | State "spotify-premium.0.devices.38f91072c7a19b496b75e6f08aa3a88278714f5a.isAvailable" has no existing object, this might lead to an error in future versions
spotify-premium.0 | 2021-06-27 07:08:51.660 | warn | State "spotify-premium.0.devices.38f91072c7a19b496b75e6f08aa3a88278714f5a.volume" has no existing object, this might lead to an error in future versions
spotify-premium.0 | 2021-06-27 07:08:51.660 | warn | State "spotify-premium.0.devices.38f91072c7a19b496b75e6f08aa3a88278714f5a.type" has no existing object, this might lead to an error in future versions
spotify-premium.0 | 2021-06-27 07:08:51.660 | warn | State "spotify-premium.0.devices.38f91072c7a19b496b75e6f08aa3a88278714f5a.name" has no existing object, this might lead to an error in future versions
spotify-premium.0 | 2021-06-27 07:08:51.660 | warn | State "spotify-premium.0.devices.38f91072c7a19b496b75e6f08aa3a88278714f5a.isRestricted" has no existing object, this might lead to an error in future versions
spotify-premium.0 | 2021-06-27 07:08:51.660 | warn | State "spotify-premium.0.devices.38f91072c7a19b496b75e6f08aa3a88278714f5a.isActive" has no existing object, this might lead to an error in future versions
spotify-premium.0 | 2021-06-27 07:08:51.659 | warn | State "spotify-premium.0.devices.38f91072c7a19b496b75e6f08aa3a88278714f5a.id" has no existing object, this might lead to an error in future versions
spotify-premium.0 | 2021-06-27 07:08:51.658 | warn | State "spotify-premium.0.devices.38f91072c7a19b496b75e6f08aa3a88278714f5a.useForPlayback" has no existing object, this might lead to an error in future versions


</body>
</html>`

**Comment by Apollon77** [comment]
please test 1.1.1
