### ISSUE TITLE
js-controller 3.3.x Update verursacht LOG Einträge

### ISSUE THREAD

**Issue by JBSullivan** [iobroker-community-adapters/ioBroker.spotify-premium#95]
Wie mittlerweile bekannt sein dürfte verursacht das Update des js-controller 3.3.x in diversen Adapter error Meldungen im LOG.

So auch hier.

`

spotify-premium.0 | 2021-05-02 11:38:23.158 | info | (8336) State value to set for "spotify-premium.0.playlists.xxxxxxxxxxxxxxxxxxxxxxxx.trackListArray" has to be type "string" but received type "object"
-- | -- | -- | --

`

**Comment by Apollon77** [comment]
Please chekc GitHub version

**Comment by JBSullivan** [comment]
Mit GitHub Version ist keine Authentifizierung mehr möglich. Adapter bleibt gelb, trotz korrekt durchgeführter Authentifizierung

**Comment by JBSullivan** [comment]
Ich habe jetzt ein Rollback auf die Version 1.0.0. gemacht. In der neuen Version 1.1.0 wird nach der Authentifizierung die UserID nicht angelegt. In der 1.0.0 funktioniert das einwandfrei.

**Comment by Apollon77** [comment]
O, dann ehrlich bin ich erstmal raus. DIe 1.0.0 ist aus 2018 ... seither gibt es viele commits die scheinbar nie released wurden.

Vllt hat @twonky4  noch ein letztes mal zeit hier bei seinem alten Adapter zu supporten Ihn lauffähig u bekommen damit die Community eine Basis hat um weiterzumachen. Mir fehlt gerade die Zeit dazu.

**Comment by GermanBluefox** [comment]
Please test 1.1.1

**Comment by JBSullivan** [comment]
Leider Nein :(

Adapter aus dem GIT auf 1.1.1 angehoben neu eingelesen, Objekte gelöscht und Instanz neu gestartet. Authorisierungslink generiert und Antwort Link entsprechend in den Objektpfad spotify-premium.0.authorization.authorizationReturnUri eingetragen.

Für einen kurzen Moment flashte eine UserID auf und Authorisierung wurde auf True gesetzt. Dann sofort UserID verschwunden und Auth. wieder false  mit folgender Meldung im LOG.

`
<html>
<body>


spotify-premium.0 | 2021-07-22 16:09:32.516 | error | (884) exception by stop: Promise.all(...).then(...).nodeify is not a function
-- | -- | -- | --
spotify-premium.0 | 2021-07-22 16:09:32.504 | error | (884) Cannot read property 'push' of undefined
spotify-premium.0 | 2021-07-22 16:09:32.503 | error | at C:\iobroker\GLT\node_modules\iobroker.spotify-premium\main.js:905:25
spotify-premium.0 | 2021-07-22 16:09:32.503 | error | at fn (C:\iobroker\GLT\node_modules\iobroker.spotify-premium\main.js:820:19)
spotify-premium.0 | 2021-07-22 16:09:32.503 | error | (884) TypeError: Cannot read property 'push' of undefined
spotify-premium.0 | 2021-07-22 16:09:32.503 | error | (884) unhandled promise rejection: Cannot read property 'push' of undefined
spotify-premium.0 | 2021-07-22 16:09:32.497 | error | (884) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().


</body>
</html>`

**Comment by GermanBluefox** [comment]
Und 1.1.3?

**Comment by JBSullivan** [comment]
Leider noch schlimmer - Die Instanz wird rot, somit kann man den Auth. Link gar nicht generieren, weil das nur bei einer "gelben" Instanz funktioniert. Hier die Meldungen dazu.

`
<html>
<body>


host.GLT(GLT) | 2021-07-22 20:22:47.031 | error | instance system.adapter.spotify-premium.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
-- | -- | -- | --
spotify-premium.0 | 2021-07-22 20:22:46.414 | error | (9288) Cannot read property 'name' of undefined
spotify-premium.0 | 2021-07-22 20:22:46.414 | error | at C:\iobroker\GLT\node_modules\iobroker.spotify-premium\main.js:684:51
spotify-premium.0 | 2021-07-22 20:22:46.414 | error | at Object.setValue (C:\iobroker\GLT\node_modules\iobroker.spotify-premium\lib\cache.js:213:13)
spotify-premium.0 | 2021-07-22 20:22:46.414 | error | at trigger (C:\iobroker\GLT\node_modules\iobroker.spotify-premium\lib\cache.js:223:14)
spotify-premium.0 | 2021-07-22 20:22:46.414 | error | at Array.forEach (<anonymous>)
spotify-premium.0 | 2021-07-22 20:22:46.414 | error | at C:\iobroker\GLT\node_modules\iobroker.spotify-premium\lib\cache.js:229:19
spotify-premium.0 | 2021-07-22 20:22:46.414 | error | at Object.listenOnHtmlTracklist [as func] (C:\iobroker\GLT\node_modules\iobroker.spotify-premium\main.js:2035:33)
spotify-premium.0 | 2021-07-22 20:22:46.414 | error | (9288) TypeError: Cannot read property 'name' of undefined
spotify-premium.0 | 2021-07-22 20:22:46.414 | error | (9288) unhandled promise rejection: Cannot read property 'name' of undefined
spotify-premium.0 | 2021-07-22 20:22:46.413 | error | (9288) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
spotify-premium.0 | 2021-07-22 20:22:46.405 | error | (9288) Cannot read property 'name' of undefined
spotify-premium.0 | 2021-07-22 20:22:46.405 | error | at processImmediate (internal/timers.js:461:21)
spotify-premium.0 | 2021-07-22 20:22:46.405 | error | at Immediate.<anonymous> (C:\iobroker\GLT\node_modules\iobroker.js-controller\lib\adapter.js:5706:41)
spotify-premium.0 | 2021-07-22 20:22:46.405 | error | at Object.stateChange (C:\iobroker\GLT\node_modules\iobroker.spotify-premium\main.js:56:43)
spotify-premium.0 | 2021-07-22 20:22:46.405 | error | at Object.setExternal (C:\iobroker\GLT\node_modules\iobroker.spotify-premium\lib\cache.js:262:5)
spotify-premium.0 | 2021-07-22 20:22:46.405 | error | at trigger (C:\iobroker\GLT\node_modules\iobroker.spotify-premium\lib\cache.js:223:14)
spotify-premium.0 | 2021-07-22 20:22:46.405 | error | at Array.forEach (<anonymous>)
spotify-premium.0 | 2021-07-22 20:22:46.405 | error | at C:\iobroker\GLT\node_modules\iobroker.spotify-premium\lib\cache.js:229:19
spotify-premium.0 | 2021-07-22 20:22:46.405 | error | at Object.listenOnHtmlTracklist [as func] (C:\iobroker\GLT\node_modules\iobroker.spotify-premium\main.js:2035:33)
spotify-premium.0 | 2021-07-22 20:22:46.405 | error | (9288) TypeError: Cannot read property 'name' of undefined
spotify-premium.0 | 2021-07-22 20:22:46.401 | error | (9288) uncaught exception: Cannot read property 'name' of undefined
host.GLT(GLT) | 2021-07-22 20:22:42.411 | info | instance system.adapter.spotify-premium.0 started with pid 9288
host.GLT(GLT) | 2021-07-22 20:22:40.510 | info | instance system.adapter.spotify-premium.0 terminated with code null ()


</body>
</html>`

**Comment by JBSullivan** [comment]
So, ich bin nochmal auf die 1.0.0 zurück und habe dort die Authentifizierung erfolgreich abgeschlossen. Dann auf die 1.1.3 und BINGO dann geht es.
Von der 1.1.1 auf die 1.1.3 funktioniert nicht. Es muss offensichtlich einmal eine funktionierende Authentifizierung vorhanden gewesen sein.

**Comment by GermanBluefox** [comment]
> So, ich bin nochmal auf die 1.0.0 zurück und habe dort die Authentifizierung erfolgreich abgeschlossen. Dann auf die 1.1.3 und BINGO dann geht es.
> Von der 1.1.1 auf die 1.1.3 funktioniert nicht. Es muss offensichtlich einmal eine funktionierende Authentifizierung vorhanden gewesen sein.

Nein. Ich habe komplett neu mit 1.1.3 geschafft.

**Comment by GermanBluefox** [comment]
Please test 1.1.4
